// Journal des bugs — VERSIONNÉ dans le dépôt (source de vérité des statuts).
// Chaque bug : identifiant unique, description, statut, dates (détection /
// résolution) et métadonnées (sévérité, zone, version du correctif).
// Les bugs SIGNALÉS PAR LES UTILISATEURS arrivent en plus et sont triés ici par le
// mainteneur quand ils sont pris en charge / résolus.
//
// Bilingue : chaque champ textuel a sa variante `_en` (titre_en / description_en /
// correctif_en / zone_en), affichée quand la langue d'interface est l'anglais.
//
// statut   : "resolu" | "en_attente"
// severite : "critique" | "majeur" | "mineur"
// Auteur : Brice Kengni Zanguim
export const BUGS = [
  {
    id: "BUG-footer-light-01", titre: "Mode clair : liens du bas de page peu lisibles (gris sur fond sombre)",
    titre_en: "Light mode: footer links hard to read (grey on dark)",
    description: "En mode clair, les liens du pied de page sous « Les espaces » et « Le projet » (Transcrire, Traduire, Accueil…) apparaissaient en gris foncé sur le footer sombre, quasi illisibles.",
    description_en: "In light mode, the footer navigation links in the two columns (Transcribe, Translate, Home…) appeared dark grey on the dark footer, barely readable.",
    statut: "resolu", severite: "mineur", zone: "Design / thème", zone_en: "Design / theme",
    detecte_le: "2026-07-23", resolu_le: "2026-07-23", version: "v338",
    correctif: "Le pied de page est toujours sombre : la couleur de ces liens est désormais fixée en clair (au lieu de suivre le thème), donc lisible en mode clair comme en sombre.",
    correctif_en: "The footer is always dark: these links now use a fixed light colour (instead of following the theme), so they read well in both light and dark modes.",
  },
  {
    id: "BUG-U-mrvvamtx-5393", titre: "Textes peu lisibles en mode clair (hors cadre, sur le fond)",
    titre_en: "Hard-to-read texts in light mode (outside frames, over the background)",
    description: "En mode clair, certains textes placés directement sur l'arrière-plan (hors cadre), comme les phrases d'introduction des pages, manquaient de contraste et étaient difficiles à lire.",
    description_en: "In light mode, some texts placed directly over the background (outside frames), such as page intro lines, lacked contrast and were hard to read.",
    statut: "resolu", severite: "majeur", zone: "Interface", zone_en: "Interface",
    detecte_le: "2026-07-22", resolu_le: "2026-07-22", version: "v335",
    correctif: "Ces textes d'introduction posés sur le fond reçoivent désormais un discret cadre en verre dépoli (léger flou) qui masque le motif derrière eux : la lecture est nette dans les deux modes, sans toucher au décor.",
    correctif_en: "These on-background intro texts now sit on a subtle frosted-glass panel (slight blur) that masks the pattern behind them: crisp reading in both modes, without changing the decoration.",
  },
  {
    id: "BUG-U-mrvvdqx9-517", titre: "Trop peu de choix dans « Zone concernée » du signalement",
    titre_en: "Too few choices in the bug report's “Area concerned”",
    description: "Le menu « Zone concernée » du formulaire de signalement ne proposait que quelques catégories, insuffisantes pour bien situer un problème.",
    description_en: "The “Area concerned” menu in the bug report form offered only a few categories, too few to properly locate an issue.",
    statut: "resolu", severite: "majeur", zone: "Interface", zone_en: "Interface",
    detecte_le: "2026-07-22", resolu_le: "2026-07-22", version: "v335",
    correctif: "La liste des zones a été enrichie (Traduire, Transcrire, Explorer, Demander, Notifications, Profil, Langues, Partage, Design, Traduction de l'app, Vitesse…) pour situer précisément chaque signalement.",
    correctif_en: "The list of areas was expanded (Translate, Transcribe, Explore, Request, Notifications, Profile, Languages, Sharing, Design, App translation, Speed…) to pinpoint each report.",
  },
  {
    id: "BUG-U-mrw5ad2f-6561", titre: "Texte resté en français en mode anglais (« Apparaîtra comme »)",
    titre_en: "Text stayed in French in English mode (“Apparaîtra comme”)",
    description: "Sur la page Profil, dans la section « Nom affiché dans la bibliothèque », l'aperçu du nom affichait « Apparaîtra comme : » en français même quand l'interface était en anglais.",
    description_en: "On the Profile page, in the “Name shown in the library” section, the name preview showed “Apparaîtra comme:” in French even when the interface was in English.",
    statut: "resolu", severite: "critique", zone: "Interface", zone_en: "Interface",
    detecte_le: "2026-07-22", resolu_le: "2026-07-22", version: "v335",
    correctif: "L'aperçu du nom passe désormais par le système de traduction : « Apparaîtra comme… » en français, « Will appear as… » en anglais, selon la langue choisie.",
    correctif_en: "The name preview now goes through the translation system: “Apparaîtra comme…” in French, “Will appear as…” in English, depending on the chosen language.",
  },
  {
    id: "BUG-U-mrmae78s-7670", titre: "Deux propositions vides regroupées, sans mot ni bouton, dans Explorer",
    titre_en: "Two empty entries grouped together, with no word or button, in Explorer",
    description: "Dans Explorer, deux propositions apparaissaient regroupées en une seule sans mot indiqué, et en les ouvrant on voyait deux cadres vides, sans bouton pour écouter l'audio ni afficher la traduction.",
    description_en: "In Explorer, two entries appeared grouped together with no word shown, and opening them revealed two empty cards, with no button to play audio or show the translation.",
    statut: "resolu", severite: "mineur", zone: "Explorer", zone_en: "Explorer",
    detecte_le: "2026-07-15", resolu_le: "2026-07-21", version: "v240",
    correctif: "La cause était de rares lignes totalement vides en base (envois anciens/malformés, sans mot, ni traduction, ni audio). Explorer les ignore désormais à l'affichage : elles ne forment plus de groupe fantôme et seules les vraies contributions apparaissent.",
    correctif_en: "The cause was a few completely empty rows in the database (old/malformed sends, with no word, translation or audio). Explorer now ignores them on display: they no longer form a ghost group and only real contributions appear.",
  },
  {
    id: "BUG-U-mrtcyz9u-8933", titre: "Notification de demande impossible à ouvrir",
    titre_en: "Request notification could not be opened",
    description: "Une notification indiquant qu'un utilisateur souhaitait une traduction ou une prononciation dans ta langue ne pouvait pas être ouverte : rien ne se passait au clic, impossible d'aller aider la personne.",
    description_en: "A notification saying a user wanted a translation or pronunciation in your language could not be opened: clicking it did nothing, so there was no way to go and help.",
    statut: "resolu", severite: "critique", zone: "Notifications", zone_en: "Notifications",
    detecte_le: "2026-07-20", resolu_le: "2026-07-20", version: "v242",
    correctif: "Chaque notification est désormais cliquable et mène droit là où agir : une demande t'emmène sur la page Traduire ou Transcrire avec le mot déjà en place ; dès que tu réponds, la personne qui avait fait la demande est prévenue automatiquement. Les retours sur tes contributions (votes, améliorations) ouvrent le mot concerné dans la bibliothèque.",
    correctif_en: "Every notification is now clickable and leads straight to where you can act: a request takes you to the Translate or Transcribe page with the word already filled in; as soon as you answer, the person who asked is notified automatically. Feedback on your contributions (votes, improvements) opens the relevant word in the library.",
  },
  {
    id: "BUG-010", titre: "Page vide après changement de langue sur « Mon profil »",
    titre_en: "Blank page after switching language on “My profile”",
    description: "Sur la page « Mon profil », changer la langue (français ↔ anglais) rechargeait la page mais laissait le corps vide ; il fallait cliquer sur un bouton du menu pour réafficher une page.",
    description_en: "On the “My profile” page, switching language (French ↔ English) reloaded the page but left the body blank; you had to click a menu button to show a page again.",
    statut: "resolu", severite: "majeur", zone: "Interface", zone_en: "Interface",
    detecte_le: "2026-07-18", resolu_le: "2026-07-18", version: "v194",
    correctif: "La page affichée « par défaut » au démarrage était le profil, ce qui trompait la protection anti-doublon du menu et empêchait le réaffichage. Corrigé par un état de départ neutre : chaque page se réaffiche correctement après un changement de langue.",
    correctif_en: "The page shown “by default” at startup was the profile, which fooled the navigation's duplicate guard and prevented redisplay. Fixed with a neutral start state: every page redisplays correctly after a language change.",
  },
  {
    id: "BUG-001", titre: "Certains envois ne partaient pas (données)",
    titre_en: "Some sends didn't go through (data)",
    description: "En cliquant sur « Envoyer les données » avec beaucoup de contributions, quelques-unes étaient comptées comme échouées alors qu'elles avaient bien été enregistrées : le résultat de l'envoi était mal interprété.",
    description_en: "When clicking “Send data” with many contributions, a few were counted as failed even though they had been saved: the send result was misread.",
    statut: "resolu", severite: "critique", zone: "Envoi / synchro", zone_en: "Sending / sync",
    detecte_le: "2026-07-12", resolu_le: "2026-07-13", version: "v76",
    correctif: "L'application vérifie désormais ce qui est réellement enregistré et renvoie automatiquement ce qui manque, jusqu'à confirmation ; deux groupes distinguent « envoyés » et « à renvoyer ».",
    correctif_en: "The app now checks what is actually saved and automatically resends what's missing, until confirmation; two groups distinguish “sent” and “to resend”.",
  },
  {
    id: "BUG-002", titre: "Un même mot pouvait être reproposé au même utilisateur",
    titre_en: "The same word could be re-offered to the same user",
    description: "Un item déjà traduit/transcrit par un utilisateur pouvait lui être reproposé (le même mot existait sous plusieurs identifiants, ex. entre « mots » et le dictionnaire).",
    description_en: "An item already translated/transcribed by a user could be re-offered to them (the same word existed under several IDs, e.g. between “words” and the dictionary).",
    statut: "resolu", severite: "majeur", zone: "Propositions", zone_en: "Suggestions",
    detecte_le: "2026-07-13", resolu_le: "2026-07-13", version: "v77",
    correctif: "Anti-répétition par utilisateur, dédup par texte normalisé, reconstruit depuis les contributions réelles. Tirage aléatoire parmi les non-faits.",
    correctif_en: "Per-user anti-repetition, dedup by normalized text, rebuilt from actual contributions. Random pick among the undone.",
  },
  {
    id: "BUG-003", titre: "Micro non détecté sur PC (portable AMD)",
    titre_en: "Microphone not detected on PC (AMD laptop)",
    description: "Sur PC, l'enregistrement audio échoue (« aucun micro détecté ») alors qu'il fonctionne sur mobile. Le micro interne est un micro numérique (DMIC) rattaché au co-processeur audio AMD ; le noyau Linux actuel lie un pilote qui ne l'expose pas.",
    description_en: "On PC, audio recording fails (“no microphone detected”) while it works on mobile. The internal microphone is a digital mic (DMIC) attached to the AMD audio co-processor; the current Linux kernel binds a driver that doesn't expose it.",
    statut: "en_attente", severite: "majeur", zone: "Audio / système", zone_en: "Audio / system",
    detecte_le: "2026-07-13", resolu_le: "", version: "",
    correctif: "En cours : test d'un noyau plus récent qui prend en charge le micro interne. Contournement fiable : micro/casque USB.",
    correctif_en: "In progress: testing a newer kernel that supports the internal microphone. Reliable workaround: USB mic/headset.",
  },
  {
    id: "BUG-004", titre: "Menus déroulants mal positionnés (PC)",
    titre_en: "Dropdown menus misplaced (PC)",
    description: "Sur PC, un menu déroulant (village, rôle…) s'ouvrait ailleurs que sous son champ.",
    description_en: "On PC, a dropdown menu (village, role…) opened somewhere other than under its field.",
    statut: "resolu", severite: "majeur", zone: "Interface", zone_en: "Interface",
    detecte_le: "2026-07-13", resolu_le: "2026-07-13", version: "v70",
    correctif: "Correction de la superposition qui décalait l'ouverture ; le menu s'affiche de nouveau juste sous son champ.",
    correctif_en: "Fixed the overlay that shifted the opening; the menu shows again right under its field.",
  },
  {
    id: "BUG-005", titre: "Clavier ngiemboon s'ouvrait au défilement",
    titre_en: "Ngiemboon keyboard opened on scroll",
    description: "Un simple défilement démarrant sur le champ ouvrait le clavier et pouvait insérer des lettres parasites.",
    description_en: "A simple scroll starting on the field opened the keyboard and could insert stray letters.",
    statut: "resolu", severite: "mineur", zone: "Clavier", zone_en: "Keyboard",
    detecte_le: "2026-07-12", resolu_le: "2026-07-12", version: "v54",
    correctif: "Ouverture au vrai tap uniquement (immobile < 10 px et < 500 ms) ; suivi du mouvement au niveau document.",
    correctif_en: "Opens on a real tap only (still < 10 px and < 500 ms); movement tracked at document level.",
  },
  {
    id: "BUG-008", titre: "Version en retard sur un appareil (cache navigateur)",
    titre_en: "Version behind on a device (browser cache)",
    description: "Après une mise à jour, un appareil pouvait rester sur une ancienne version (ex. mobile en v79 alors que le PC était en v83), obligeant à un rechargement forcé (Ctrl+Shift+R).",
    description_en: "After an update, a device could stay on an old version (e.g. mobile on v79 while the PC was on v83), forcing a hard reload (Ctrl+Shift+R).",
    statut: "resolu", severite: "majeur", zone: "Interface", zone_en: "Interface",
    detecte_le: "2026-07-13", resolu_le: "2026-07-13", version: "v84",
    correctif: "L'application détecte la nouvelle version et propose de l'installer en un clic (bannière « Nouvelle version disponible »), sans rechargement manuel.",
    correctif_en: "The app detects the new version and offers to install it in one click (“New version available” banner), with no manual reload.",
  },
  {
    id: "BUG-007", titre: "Menus déroulants d'Explorer cachés par les cartes",
    titre_en: "Explore dropdowns hidden by the cards",
    description: "Dans « Explorer », un menu déroulant (filtres) était partiellement occulté par les cartes situées en dessous quand il s'ouvrait (superposition).",
    description_en: "In “Explore”, a dropdown (filters) was partly hidden by the cards below when it opened (overlap).",
    statut: "resolu", severite: "majeur", zone: "Interface", zone_en: "Interface",
    detecte_le: "2026-07-13", resolu_le: "2026-07-13", version: "v79",
    correctif: "Le menu s'affiche désormais au premier plan, bien ancré sous son champ, sans être masqué par les cartes, à l'identique sur PC et mobile.",
    correctif_en: "The menu now shows in the foreground, anchored under its field, not hidden by the cards, identically on PC and mobile.",
  },
  {
    id: "BUG-009", titre: "La bannière de mise à jour réapparaissait après la mise à jour",
    titre_en: "The update banner reappeared after updating",
    description: "Après avoir cliqué sur « Mettre à jour », la mise à jour se faisait mais la bannière « Nouvelle version disponible » revenait indéfiniment ; elle ne disparaissait qu'avec un rechargement forcé (Ctrl+Shift+R).",
    description_en: "After clicking “Update”, the update happened but the “New version available” banner came back indefinitely; it only went away with a hard reload (Ctrl+Shift+R).",
    statut: "resolu", severite: "majeur", zone: "Interface / mise à jour", zone_en: "Interface / update",
    detecte_le: "2026-07-13", resolu_le: "2026-07-13", version: "v88",
    correctif: "La mise à jour s'installe correctement du premier coup et la bannière se referme d'elle-même dès que l'application est réellement à jour.",
    correctif_en: "The update installs correctly on the first try and the banner closes on its own as soon as the app is truly up to date.",
  },
  {
    id: "BUG-006", titre: "Audio non réinitialisé au mot suivant",
    titre_en: "Audio not reset on the next word",
    description: "En passant au mot suivant, un audio enregistré mais non sauvegardé pouvait « coller » à la contribution d'après.",
    description_en: "When moving to the next word, a recorded but unsaved audio could “stick” to the following contribution.",
    statut: "resolu", severite: "majeur", zone: "Audio", zone_en: "Audio",
    detecte_le: "2026-07-12", resolu_le: "2026-07-12", version: "v54",
    correctif: "Remise à zéro du travail en cours (texte, note, domaine, audio) à chaque changement de mot ou d'espace.",
    correctif_en: "Resets the work in progress (text, note, domain, audio) on every word or space change.",
  },
];
