// Configuration de l'application de collecte.
//
// ENDPOINT vide ("")   → serveur local Python (server/collecte_server.py),
//                        données sauvegardées en 4 copies sur ta machine.
// ENDPOINT renseigné    → URL "…/exec" de ton Google Apps Script : les données
//                        arrivent dans ta Google Sheet + tes audios dans ta
//                        Google Drive (gratuit, sans machine allumée).
//
// VILLAGES : liste des villages/quartiers liés aux variantes du ngiemboon,
// proposée au contributeur (+ option « Autre » pour saisir un choix libre).
// Édite librement cette liste (ajoute les quartiers de Bangang, etc.).
export const CONFIG = {
  ENDPOINT: "https://script.google.com/macros/s/AKfycbx_jaNM030YgVI2RIw0p6wY8lXDMztf7xNY3TqX6TkPxxIGCjtuU6jfN0EJVIQ8PvTa/exec",
  INDICATIF_DEFAUT: "+237", // Cameroun
  // Indicatifs téléphoniques (drapeau + pays + code). Cameroun en tête, puis les
  // destinations les plus courantes pour la diaspora ngiemboon/camerounaise, puis le
  // reste du monde (liste volontairement quasi-exhaustive, ~170 pays/territoires : LANGIAL
  // a une visée mondiale, aucun visiteur ne doit être bloqué faute d'indicatif listé). En
  // ULTIME secours (territoire disputé, indicatif oublié malgré tout), le sélecteur propose
  // toujours une option « Autre » qui ouvre un champ libre (cf. initIndicatifs()) : cette
  // liste n'a donc plus besoin d'être parfaite pour ne JAMAIS bloquer un profil.
  INDICATIFS: [
    { f: "🇨🇲", p: "Cameroun", d: "+237" },
    { f: "🇫🇷", p: "France", d: "+33" },
    { f: "🇧🇪", p: "Belgique", d: "+32" },
    { f: "🇨🇭", p: "Suisse", d: "+41" },
    { f: "🇩🇪", p: "Allemagne", d: "+49" },
    { f: "🇬🇧", p: "Royaume-Uni", d: "+44" },
    { f: "🇺🇸", p: "États-Unis", d: "+1" },
    { f: "🇨🇦", p: "Canada", d: "+1" },
    { f: "🇮🇹", p: "Italie", d: "+39" },
    { f: "🇪🇸", p: "Espagne", d: "+34" },
    { f: "🇳🇱", p: "Pays-Bas", d: "+31" },
    { f: "🇳🇬", p: "Nigéria", d: "+234" },
    { f: "🇬🇦", p: "Gabon", d: "+241" },
    { f: "🇹🇩", p: "Tchad", d: "+235" },
    { f: "🇨🇫", p: "Centrafrique", d: "+236" },
    { f: "🇬🇶", p: "Guinée équatoriale", d: "+240" },
    { f: "🇨🇬", p: "Congo", d: "+242" },
    { f: "🇨🇩", p: "RD Congo", d: "+243" },
    { f: "🇨🇮", p: "Côte d'Ivoire", d: "+225" },
    { f: "🇸🇳", p: "Sénégal", d: "+221" },
    { f: "🇬🇭", p: "Ghana", d: "+233" },
    { f: "🇧🇯", p: "Bénin", d: "+229" },
    { f: "🇹🇬", p: "Togo", d: "+228" },
    { f: "🇧🇫", p: "Burkina Faso", d: "+226" },
    { f: "🇲🇱", p: "Mali", d: "+223" },
    { f: "🇬🇳", p: "Guinée", d: "+224" },
    { f: "🇲🇦", p: "Maroc", d: "+212" },
    { f: "🇩🇿", p: "Algérie", d: "+213" },
    { f: "🇹🇳", p: "Tunisie", d: "+216" },
    { f: "🇿🇦", p: "Afrique du Sud", d: "+27" },
    { f: "🇰🇪", p: "Kenya", d: "+254" },
    { f: "🇨🇳", p: "Chine", d: "+86" },
    { f: "🇦🇪", p: "Émirats arabes unis", d: "+971" },
    { f: "🇧🇷", p: "Brésil", d: "+55" },
    { f: "🇮🇳", p: "Inde", d: "+91" },
    { f: "🇦🇺", p: "Australie", d: "+61" },
    // --- Reste de l'Afrique ---
    { f: "🇳🇪", p: "Niger", d: "+227" },
    { f: "🇸🇱", p: "Sierra Leone", d: "+232" },
    { f: "🇱🇷", p: "Liberia", d: "+231" },
    { f: "🇬🇲", p: "Gambie", d: "+220" },
    { f: "🇬🇼", p: "Guinée-Bissau", d: "+245" },
    { f: "🇨🇻", p: "Cap-Vert", d: "+238" },
    { f: "🇲🇷", p: "Mauritanie", d: "+222" },
    { f: "🇱🇾", p: "Libye", d: "+218" },
    { f: "🇸🇩", p: "Soudan", d: "+249" },
    { f: "🇸🇸", p: "Soudan du Sud", d: "+211" },
    { f: "🇪🇹", p: "Éthiopie", d: "+251" },
    { f: "🇪🇷", p: "Érythrée", d: "+291" },
    { f: "🇩🇯", p: "Djibouti", d: "+253" },
    { f: "🇸🇴", p: "Somalie", d: "+252" },
    { f: "🇺🇬", p: "Ouganda", d: "+256" },
    { f: "🇹🇿", p: "Tanzanie", d: "+255" },
    { f: "🇷🇼", p: "Rwanda", d: "+250" },
    { f: "🇧🇮", p: "Burundi", d: "+257" },
    { f: "🇿🇲", p: "Zambie", d: "+260" },
    { f: "🇿🇼", p: "Zimbabwe", d: "+263" },
    { f: "🇲🇼", p: "Malawi", d: "+265" },
    { f: "🇲🇿", p: "Mozambique", d: "+258" },
    { f: "🇦🇴", p: "Angola", d: "+244" },
    { f: "🇳🇦", p: "Namibie", d: "+264" },
    { f: "🇧🇼", p: "Botswana", d: "+267" },
    { f: "🇱🇸", p: "Lesotho", d: "+266" },
    { f: "🇸🇿", p: "Eswatini", d: "+268" },
    { f: "🇲🇬", p: "Madagascar", d: "+261" },
    { f: "🇲🇺", p: "Maurice", d: "+230" },
    { f: "🇰🇲", p: "Comores", d: "+269" },
    { f: "🇸🇨", p: "Seychelles", d: "+248" },
    { f: "🇸🇹", p: "Sao Tomé-et-Principe", d: "+239" },
    // --- Reste de l'Europe ---
    { f: "🇵🇹", p: "Portugal", d: "+351" },
    { f: "🇱🇺", p: "Luxembourg", d: "+352" },
    { f: "🇮🇪", p: "Irlande", d: "+353" },
    { f: "🇳🇴", p: "Norvège", d: "+47" },
    { f: "🇸🇪", p: "Suède", d: "+46" },
    { f: "🇩🇰", p: "Danemark", d: "+45" },
    { f: "🇫🇮", p: "Finlande", d: "+358" },
    { f: "🇮🇸", p: "Islande", d: "+354" },
    { f: "🇵🇱", p: "Pologne", d: "+48" },
    { f: "🇨🇿", p: "République tchèque", d: "+420" },
    { f: "🇸🇰", p: "Slovaquie", d: "+421" },
    { f: "🇦🇹", p: "Autriche", d: "+43" },
    { f: "🇭🇺", p: "Hongrie", d: "+36" },
    { f: "🇷🇴", p: "Roumanie", d: "+40" },
    { f: "🇧🇬", p: "Bulgarie", d: "+359" },
    { f: "🇬🇷", p: "Grèce", d: "+30" },
    { f: "🇭🇷", p: "Croatie", d: "+385" },
    { f: "🇷🇸", p: "Serbie", d: "+381" },
    { f: "🇧🇦", p: "Bosnie-Herzégovine", d: "+387" },
    { f: "🇸🇮", p: "Slovénie", d: "+386" },
    { f: "🇲🇰", p: "Macédoine du Nord", d: "+389" },
    { f: "🇦🇱", p: "Albanie", d: "+355" },
    { f: "🇲🇪", p: "Monténégro", d: "+382" },
    { f: "🇺🇦", p: "Ukraine", d: "+380" },
    { f: "🇧🇾", p: "Biélorussie", d: "+375" },
    { f: "🇷🇺", p: "Russie", d: "+7" },
    { f: "🇲🇩", p: "Moldavie", d: "+373" },
    { f: "🇱🇹", p: "Lituanie", d: "+370" },
    { f: "🇱🇻", p: "Lettonie", d: "+371" },
    { f: "🇪🇪", p: "Estonie", d: "+372" },
    { f: "🇨🇾", p: "Chypre", d: "+357" },
    { f: "🇲🇹", p: "Malte", d: "+356" },
    { f: "🇹🇷", p: "Turquie", d: "+90" },
    // --- Amériques ---
    { f: "🇲🇽", p: "Mexique", d: "+52" },
    { f: "🇦🇷", p: "Argentine", d: "+54" },
    { f: "🇨🇱", p: "Chili", d: "+56" },
    { f: "🇨🇴", p: "Colombie", d: "+57" },
    { f: "🇵🇪", p: "Pérou", d: "+51" },
    { f: "🇻🇪", p: "Venezuela", d: "+58" },
    { f: "🇪🇨", p: "Équateur", d: "+593" },
    { f: "🇧🇴", p: "Bolivie", d: "+591" },
    { f: "🇵🇾", p: "Paraguay", d: "+595" },
    { f: "🇺🇾", p: "Uruguay", d: "+598" },
    { f: "🇬🇾", p: "Guyana", d: "+592" },
    { f: "🇸🇷", p: "Suriname", d: "+597" },
    { f: "🇨🇺", p: "Cuba", d: "+53" },
    { f: "🇩🇴", p: "République dominicaine", d: "+1" },
    { f: "🇭🇹", p: "Haïti", d: "+509" },
    { f: "🇯🇲", p: "Jamaïque", d: "+1" },
    { f: "🇹🇹", p: "Trinité-et-Tobago", d: "+1" },
    { f: "🇬🇹", p: "Guatemala", d: "+502" },
    { f: "🇭🇳", p: "Honduras", d: "+504" },
    { f: "🇸🇻", p: "Salvador", d: "+503" },
    { f: "🇳🇮", p: "Nicaragua", d: "+505" },
    { f: "🇨🇷", p: "Costa Rica", d: "+506" },
    { f: "🇵🇦", p: "Panama", d: "+507" },
    // --- Asie ---
    { f: "🇯🇵", p: "Japon", d: "+81" },
    { f: "🇰🇷", p: "Corée du Sud", d: "+82" },
    { f: "🇰🇵", p: "Corée du Nord", d: "+850" },
    { f: "🇻🇳", p: "Vietnam", d: "+84" },
    { f: "🇹🇭", p: "Thaïlande", d: "+66" },
    { f: "🇵🇭", p: "Philippines", d: "+63" },
    { f: "🇮🇩", p: "Indonésie", d: "+62" },
    { f: "🇲🇾", p: "Malaisie", d: "+60" },
    { f: "🇸🇬", p: "Singapour", d: "+65" },
    { f: "🇵🇰", p: "Pakistan", d: "+92" },
    { f: "🇧🇩", p: "Bangladesh", d: "+880" },
    { f: "🇱🇰", p: "Sri Lanka", d: "+94" },
    { f: "🇳🇵", p: "Népal", d: "+977" },
    { f: "🇦🇫", p: "Afghanistan", d: "+93" },
    { f: "🇮🇷", p: "Iran", d: "+98" },
    { f: "🇮🇶", p: "Irak", d: "+964" },
    { f: "🇸🇦", p: "Arabie saoudite", d: "+966" },
    { f: "🇶🇦", p: "Qatar", d: "+974" },
    { f: "🇰🇼", p: "Koweït", d: "+965" },
    { f: "🇧🇭", p: "Bahreïn", d: "+973" },
    { f: "🇴🇲", p: "Oman", d: "+968" },
    { f: "🇯🇴", p: "Jordanie", d: "+962" },
    { f: "🇱🇧", p: "Liban", d: "+961" },
    { f: "🇸🇾", p: "Syrie", d: "+963" },
    { f: "🇮🇱", p: "Israël", d: "+972" },
    { f: "🇵🇸", p: "Palestine", d: "+970" },
    { f: "🇾🇪", p: "Yémen", d: "+967" },
    { f: "🇰🇿", p: "Kazakhstan", d: "+7" },
    { f: "🇺🇿", p: "Ouzbékistan", d: "+998" },
    { f: "🇹🇲", p: "Turkménistan", d: "+993" },
    { f: "🇹🇯", p: "Tadjikistan", d: "+992" },
    { f: "🇰🇬", p: "Kirghizistan", d: "+996" },
    { f: "🇲🇳", p: "Mongolie", d: "+976" },
    { f: "🇲🇲", p: "Myanmar", d: "+95" },
    { f: "🇰🇭", p: "Cambodge", d: "+855" },
    { f: "🇱🇦", p: "Laos", d: "+856" },
    { f: "🇹🇼", p: "Taïwan", d: "+886" },
    { f: "🇭🇰", p: "Hong Kong", d: "+852" },
    { f: "🇲🇴", p: "Macao", d: "+853" },
    // --- Océanie ---
    { f: "🇳🇿", p: "Nouvelle-Zélande", d: "+64" },
    { f: "🇫🇯", p: "Fidji", d: "+679" },
    { f: "🇵🇬", p: "Papouasie-Nouvelle-Guinée", d: "+675" },
  ],
  VILLAGES: [
    // Villages/groupements de l'aire ngiemboon (variantes principales).
    "Bangang",
    "Batcham",
    "Balatchi",
    "Bamougong",
    "Balessing",
    "Batang",
    // — Quartiers/localités du groupement Bangang (source : Wikipédia FR, à affiner
    //    avec la connaissance locale ; la combobox filtre à la frappe + « Autre »
    //    reste disponible pour toute localité manquante). —
    "Babeughang", "Bachio", "Badatchio", "Badengang", "Baghang 1", "Baghang 2",
    "Bakapfong", "Baladjeutsa", "Balepi", "Kofong", "Bameguea", "Bantsiet",
    "Bamela", "Balie", "Balafotio", "Balekeu", "Bamekeng-Mekoup", "Batsepou",
    "Bantsinla", "Bamessa", "Bamboue", "Batsa'a", "Nzemetsuet", "Baletia",
    "Balekouet", "Tchuelekouet 1", "Tchuelekouet 2", "Bamelang", "Bamelio",
    "Bassessa", "Bandengang", "Bankack", "Balewa", "Bangouo", "Fomelie",
    "Kontse", "Mantah", "Mepibea", "Meto", "Njuinla 1", "Bassoh", "Nkop",
    "Balouo", "Bamemba", "Bankouop", "Bambiete", "Bazuintim", "Tomogang 1",
    "Tomogang 2", "Tsopeua", "Nzindong", "Biete", "Zemezong", "Zemtchuet",
  ],
};
