// Équivalents ANGLAIS des items SOURCES (le mot/nombre à traduire ou transcrire), afin
// d'afficher le prompt dans la langue d'interface. Un utilisateur passé en anglais lit
// l'item en anglais pour bien le comprendre avant de traduire/transcrire.
//
// Le stockage de la contribution garde TOUJOURS le mot source CANONIQUE (français) →
// le regroupement Explorer reste cohérent quelle que soit la langue. Ce dictionnaire
// couvre l'intégralité des mots et nombres proposés ; les lettres isolées sont identiques.
// Extensible : ajouter une paire ici enrichit la couverture.
//
// Auteur : Brice Kengni Zanguim.

// Chiffres et nombres.
const NOMBRES = {
  "zéro": "zero", "un": "one", "deux": "two", "trois": "three", "quatre": "four", "cinq": "five", "six": "six", "sept": "seven", "huit": "eight", "neuf": "nine",
  "dix": "ten", "onze": "eleven", "douze": "twelve", "treize": "thirteen", "quatorze": "fourteen",
  "quinze": "fifteen", "seize": "sixteen", "dix-sept": "seventeen", "dix-huit": "eighteen",
  "dix-neuf": "nineteen", "vingt": "twenty", "vingt et un": "twenty-one", "vingt-deux": "twenty-two",
  "vingt-trois": "twenty-three", "vingt-quatre": "twenty-four", "vingt-cinq": "twenty-five",
  "vingt-six": "twenty-six", "vingt-sept": "twenty-seven", "vingt-huit": "twenty-eight",
  "vingt-neuf": "twenty-nine", "trente": "thirty", "trente et un": "thirty-one",
  "trente-deux": "thirty-two", "trente-trois": "thirty-three", "trente-quatre": "thirty-four",
  "trente-cinq": "thirty-five", "trente-six": "thirty-six", "trente-sept": "thirty-seven",
  "trente-huit": "thirty-eight", "trente-neuf": "thirty-nine", "quarante": "forty",
  "quarante et un": "forty-one", "quarante-deux": "forty-two", "quarante-trois": "forty-three",
  "quarante-quatre": "forty-four", "quarante-cinq": "forty-five", "quarante-six": "forty-six",
  "quarante-sept": "forty-seven", "quarante-huit": "forty-eight", "quarante-neuf": "forty-nine",
  "cinquante": "fifty", "cinquante et un": "fifty-one", "cinquante-deux": "fifty-two",
  "cinquante-trois": "fifty-three", "cinquante-quatre": "fifty-four", "cinquante-cinq": "fifty-five",
  "cinquante-six": "fifty-six", "cinquante-sept": "fifty-seven", "cinquante-huit": "fifty-eight",
  "cinquante-neuf": "fifty-nine", "soixante": "sixty", "soixante et un": "sixty-one",
  "soixante-deux": "sixty-two", "soixante-trois": "sixty-three", "soixante-quatre": "sixty-four",
  "soixante-cinq": "sixty-five", "soixante-six": "sixty-six", "soixante-sept": "sixty-seven",
  "soixante-huit": "sixty-eight", "soixante-neuf": "sixty-nine", "soixante-dix": "seventy",
  "soixante et onze": "seventy-one", "soixante-douze": "seventy-two", "soixante-treize": "seventy-three",
  "soixante-quatorze": "seventy-four", "soixante-quinze": "seventy-five", "soixante-seize": "seventy-six",
  "soixante-dix-sept": "seventy-seven", "soixante-dix-huit": "seventy-eight",
  "soixante-dix-neuf": "seventy-nine", "quatre-vingts": "eighty", "quatre-vingt-un": "eighty-one",
  "quatre-vingt-deux": "eighty-two", "quatre-vingt-trois": "eighty-three",
  "quatre-vingt-quatre": "eighty-four", "quatre-vingt-cinq": "eighty-five",
  "quatre-vingt-six": "eighty-six", "quatre-vingt-sept": "eighty-seven",
  "quatre-vingt-huit": "eighty-eight", "quatre-vingt-neuf": "eighty-nine", "quatre-vingt-dix": "ninety",
  "quatre-vingt-onze": "ninety-one", "quatre-vingt-douze": "ninety-two",
  "quatre-vingt-treize": "ninety-three", "quatre-vingt-quatorze": "ninety-four",
  "quatre-vingt-quinze": "ninety-five", "quatre-vingt-seize": "ninety-six",
  "quatre-vingt-dix-sept": "ninety-seven", "quatre-vingt-dix-huit": "ninety-eight",
  "quatre-vingt-dix-neuf": "ninety-nine", "cent": "one hundred", "cent un": "one hundred and one",
  "cent dix": "one hundred and ten", "cent cinquante": "one hundred and fifty",
  "deux cents": "two hundred", "deux cent cinquante": "two hundred and fifty",
  "trois cents": "three hundred", "cinq cents": "five hundred",
  "sept cent cinquante": "seven hundred and fifty",
  "neuf cent quatre-vingt-dix-neuf": "nine hundred and ninety-nine", "mille": "one thousand",
  "mille un": "one thousand and one", "deux mille": "two thousand", "cinq mille": "five thousand",
  "dix mille": "ten thousand", "cinquante mille": "fifty thousand", "cent mille": "one hundred thousand",
  "cinq cent mille": "five hundred thousand", "un million": "one million", "deux millions": "two million",
  "dix millions": "ten million", "cent millions": "one hundred million", "un milliard": "one billion",
  "dix milliards": "ten billion", "premier": "first", "première": "first", "deuxième": "second",
  "troisième": "third", "quatrième": "fourth", "cinquième": "fifth", "sixième": "sixth",
  "septième": "seventh", "huitième": "eighth", "neuvième": "ninth", "dixième": "tenth",
  "onzième": "eleventh", "douzième": "twelfth", "treizième": "thirteenth", "quatorzième": "fourteenth",
  "quinzième": "fifteenth", "seizième": "sixteenth", "dix-septième": "seventeenth",
  "dix-huitième": "eighteenth", "dix-neuvième": "nineteenth", "vingtième": "twentieth",
  "centième": "hundredth", "millième": "thousandth", "dernier": "last", "dernière": "last",
  "avant-dernier": "second to last", "la moitié": "half", "le quart": "a quarter", "le tiers": "a third",
  "les deux tiers": "two thirds", "les trois quarts": "three quarters", "un demi": "a half",
  "un centième": "a hundredth", "un dixième": "a tenth", "un pour cent": "one percent",
  "cinquante pour cent": "fifty percent", "cent pour cent": "one hundred percent", "une paire": "a pair",
  "une dizaine": "about ten", "une douzaine": "a dozen", "une quinzaine": "about fifteen",
  "une vingtaine": "about twenty", "une trentaine": "about thirty", "une cinquantaine": "about fifty",
  "une centaine": "about a hundred", "un millier": "about a thousand", "un couple": "a couple",
  "un trio": "a trio", "une poignée": "a handful", "zéro virgule cinq": "zero point five",
  "deux virgule cinq": "two point five",
};

// Mots (tous les mots proposés). Traductions standard.
const MOTS = {
  // Parenté et personnes
  "père": "father", "mère": "mother", "enfant": "child", "fils": "son", "fille": "daughter", "frère": "brother",
  "sœur": "sister", "grand-père": "grandfather", "grand-mère": "grandmother", "mari": "husband", "femme": "woman",
  "époux": "husband", "épouse": "wife", "oncle": "uncle", "tante": "aunt", "cousin": "cousin", "cousine": "cousin",
  "neveu": "nephew", "nièce": "niece", "beau-père": "father-in-law", "belle-mère": "mother-in-law", "gendre": "son-in-law",
  "belle-fille": "daughter-in-law", "beau-frère": "brother-in-law", "belle-sœur": "sister-in-law", "jumeau": "twin",
  "jumelle": "twin", "aîné": "eldest child", "cadet": "younger child", "orphelin": "orphan", "veuf": "widower",
  "veuve": "widow", "ancêtre": "ancestor", "descendant": "descendant", "parent": "relative", "marraine": "godmother",
  "parrain": "godfather", "filleul": "godchild", "famille": "family", "ami": "friend", "amie": "friend",
  "camarade": "comrade", "voisin": "neighbour", "voisine": "neighbour", "connaissance": "acquaintance",
  "compagnon": "companion", "fiancé": "fiancé", "fiancée": "fiancée", "homme": "man", "garçon": "boy", "bébé": "baby",
  "vieillard": "old man", "adulte": "adult", "jeune": "young person", "vieux": "old man", "chef": "chief", "roi": "king",
  "reine": "queen", "prince": "prince", "princesse": "princess", "notable": "notable", "étranger": "foreigner",
  "invité": "guest", "hôte": "host", "peuple": "people", "foule": "crowd", "personne": "person", "gens": "people",
  "habitant": "inhabitant", "citoyen": "citizen", "élève": "pupil", "étudiant": "student", "maître": "master",
  "professeur": "teacher", "instituteur": "schoolteacher", "médecin": "doctor", "infirmier": "nurse", "guérisseur": "healer",
  "sorcier": "sorcerer", "prêtre": "priest", "pasteur": "pastor", "imam": "imam", "juge": "judge", "avocat": "lawyer",
  "policier": "police officer", "soldat": "soldier", "gardien": "guard", "chasseur": "hunter", "pêcheur": "fisherman",
  "cultivateur": "farmer", "éleveur": "herder", "berger": "shepherd", "forgeron": "blacksmith", "menuisier": "carpenter",
  "maçon": "mason", "tailleur": "tailor", "couturier": "dressmaker", "commerçant": "trader", "marchand": "merchant",
  "vendeur": "seller", "acheteur": "buyer", "client": "customer", "patron": "boss", "ouvrier": "worker",
  "employé": "employee", "serviteur": "servant", "esclave": "slave", "témoin": "witness", "voleur": "thief",
  "menteur": "liar", "sage": "wise person", "fou": "madman", "aveugle": "blind person", "sourd": "deaf person",
  "muet": "mute person", "boiteux": "lame person", "malade": "sick person", "héros": "hero", "ennemi": "enemy",
  "chanteur": "singer", "danseur": "dancer", "conteur": "storyteller", "musicien": "musician", "artisan": "craftsman",
  "chauffeur": "driver",
  // Corps
  "tête": "head", "crâne": "skull", "cheveu": "hair", "visage": "face", "front": "forehead", "œil": "eye",
  "sourcil": "eyebrow", "cil": "eyelash", "oreille": "ear", "nez": "nose", "joue": "cheek", "bouche": "mouth",
  "lèvre": "lip", "dent": "tooth", "gencive": "gum", "langue": "tongue", "menton": "chin", "cou": "neck", "nuque": "nape",
  "gorge": "throat", "épaule": "shoulder", "aisselle": "armpit", "bras": "arm", "coude": "elbow", "poignet": "wrist",
  "main": "hand", "paume": "palm", "doigt": "finger", "pouce": "thumb", "ongle": "nail", "poitrine": "chest",
  "sein": "breast", "ventre": "belly", "nombril": "navel", "dos": "back", "colonne": "spine", "hanche": "hip",
  "fesse": "buttock", "jambe": "leg", "cuisse": "thigh", "genou": "knee", "mollet": "calf", "cheville": "ankle",
  "talon": "heel", "pied": "foot", "orteil": "toe", "cœur": "heart", "sang": "blood", "veine": "vein", "os": "bone",
  "côte": "rib", "peau": "skin", "chair": "flesh", "muscle": "muscle", "nerf": "nerve", "cerveau": "brain",
  "poumon": "lung", "foie": "liver", "rein": "kidney", "estomac": "stomach", "intestin": "intestine", "corps": "body",
  "salive": "saliva", "larme": "tear", "sueur": "sweat", "souffle": "breath", "voix": "voice", "ombre": "shadow",
  "squelette": "skeleton", "vessie": "bladder",
  // Nature et éléments
  "eau": "water", "feu": "fire", "terre": "earth", "air": "air", "ciel": "sky", "soleil": "sun", "lune": "moon",
  "étoile": "star", "nuage": "cloud", "pluie": "rain", "vent": "wind", "orage": "storm", "éclair": "lightning",
  "tonnerre": "thunder", "arc-en-ciel": "rainbow", "rosée": "dew", "brouillard": "fog", "gelée": "frost", "glace": "ice",
  "neige": "snow", "tempête": "storm", "lumière": "light", "obscurité": "darkness", "chaleur": "heat", "froid": "cold",
  "montagne": "mountain", "colline": "hill", "vallée": "valley", "plaine": "plain", "rivière": "river", "fleuve": "river",
  "ruisseau": "stream", "lac": "lake", "étang": "pond", "mer": "sea", "océan": "ocean", "vague": "wave", "marée": "tide",
  "source": "spring", "puits": "well", "cascade": "waterfall", "île": "island", "forêt": "forest", "brousse": "bush",
  "savane": "savanna", "désert": "desert", "champ": "field", "jardin": "garden", "prairie": "meadow", "grotte": "cave",
  "rocher": "rock", "pierre": "stone", "caillou": "pebble", "sable": "sand", "poussière": "dust", "boue": "mud",
  "argile": "clay", "or": "gold", "argent": "silver", "fer": "iron", "cuivre": "copper", "charbon": "coal", "cendre": "ash",
  "fumée": "smoke", "flamme": "flame", "braise": "ember", "arbre": "tree", "branche": "branch", "écorce": "bark",
  "feuille": "leaf", "racine": "root", "épine": "thorn", "fleur": "flower", "fruit": "fruit", "graine": "seed",
  "herbe": "grass", "mousse": "moss", "champignon": "mushroom", "liane": "vine", "buisson": "bush", "chemin": "path",
  "sentier": "trail", "route": "road", "pont": "bridge", "trou": "hole", "monde": "world", "nature": "nature",
  // Animaux
  "chien": "dog", "chat": "cat", "poule": "hen", "coq": "rooster", "poussin": "chick", "canard": "duck", "oie": "goose",
  "dinde": "turkey", "pigeon": "pigeon", "perdrix": "partridge", "perroquet": "parrot", "hibou": "owl", "aigle": "eagle",
  "vautour": "vulture", "corbeau": "crow", "hirondelle": "swallow", "moineau": "sparrow", "oiseau": "bird", "chèvre": "goat",
  "chevreau": "kid", "mouton": "sheep", "agneau": "lamb", "bélier": "ram", "vache": "cow", "taureau": "bull", "veau": "calf",
  "bœuf": "ox", "cochon": "pig", "porc": "pig", "cheval": "horse", "jument": "mare", "poulain": "foal", "âne": "donkey",
  "chameau": "camel", "lapin": "rabbit", "lièvre": "hare", "écureuil": "squirrel", "hérisson": "hedgehog",
  "chauve-souris": "bat", "souris": "mouse", "rat": "rat", "éléphant": "elephant", "lion": "lion", "léopard": "leopard",
  "panthère": "panther", "hyène": "hyena", "chacal": "jackal", "renard": "fox", "singe": "monkey", "gorille": "gorilla",
  "antilope": "antelope", "biche": "doe", "buffle": "buffalo", "gazelle": "gazelle", "girafe": "giraffe", "zèbre": "zebra",
  "rhinocéros": "rhinoceros", "hippopotame": "hippopotamus", "serpent": "snake", "python": "python", "vipère": "viper",
  "lézard": "lizard", "caméléon": "chameleon", "margouillat": "gecko", "tortue": "tortoise", "crocodile": "crocodile",
  "grenouille": "frog", "crapaud": "toad", "poisson": "fish", "requin": "shark", "baleine": "whale", "dauphin": "dolphin",
  "crabe": "crab", "crevette": "shrimp", "escargot": "snail", "araignée": "spider", "abeille": "bee", "guêpe": "wasp",
  "mouche": "fly", "moustique": "mosquito", "fourmi": "ant", "termite": "termite", "cafard": "cockroach",
  "papillon": "butterfly", "chenille": "caterpillar", "ver": "worm", "sauterelle": "grasshopper", "criquet": "locust",
  "libellule": "dragonfly", "scorpion": "scorpion", "puce": "flea", "pou": "louse", "animal": "animal", "bête": "beast",
  "troupeau": "herd",
  // Nourriture
  "nourriture": "food", "repas": "meal", "viande": "meat", "œuf": "egg", "lait": "milk", "fromage": "cheese",
  "beurre": "butter", "yaourt": "yoghurt", "sel": "salt", "poivre": "pepper", "piment": "chilli", "épice": "spice",
  "gingembre": "ginger", "ail": "garlic", "oignon": "onion", "huile": "oil", "sucre": "sugar", "farine": "flour",
  "pâte": "dough", "pain": "bread", "beignet": "fritter", "galette": "flatbread", "gâteau": "cake", "bouillie": "porridge",
  "soupe": "soup", "sauce": "sauce", "ragoût": "stew", "riz": "rice", "maïs": "maize", "mil": "millet", "sorgho": "sorghum",
  "blé": "wheat", "haricot": "bean", "pois": "pea", "lentille": "lentil", "arachide": "peanut", "soja": "soybean",
  "noix": "nut", "coco": "coconut", "banane": "banana", "plantain": "plantain", "igname": "yam", "manioc": "cassava",
  "taro": "taro", "patate": "sweet potato", "pomme de terre": "potato", "tomate": "tomato", "aubergine": "eggplant",
  "gombo": "okra", "concombre": "cucumber", "courge": "squash", "citrouille": "pumpkin", "carotte": "carrot",
  "chou": "cabbage", "épinard": "spinach", "salade": "lettuce", "légume": "vegetable", "ananas": "pineapple",
  "mangue": "mango", "papaye": "papaya", "orange": "orange", "citron": "lemon", "pamplemousse": "grapefruit",
  "goyave": "guava", "pastèque": "watermelon", "melon": "melon", "raisin": "grape", "pomme": "apple",
  "fruit sec": "dried fruit", "datte": "date", "miel": "honey", "confiture": "jam", "boisson": "drink", "vin": "wine",
  "bière": "beer", "jus": "juice", "café": "coffee", "thé": "tea", "eau potable": "drinking water", "faim": "hunger",
  "soif": "thirst", "goût": "taste", "saveur": "flavour",
  // Maison, objets, outils, transport, vêtements
  "maison": "house", "case": "hut", "hutte": "hut", "cour": "courtyard", "clôture": "fence", "barrière": "gate",
  "porte": "door", "fenêtre": "window", "toit": "roof", "mur": "wall", "sol": "floor", "plafond": "ceiling",
  "poutre": "beam", "planche": "plank", "brique": "brick", "ciment": "cement", "escalier": "stairs", "chambre": "bedroom",
  "cuisine": "kitchen", "salon": "living room", "lit": "bed", "matelas": "mattress", "oreiller": "pillow", "drap": "sheet",
  "couverture": "blanket", "natte": "mat", "moustiquaire": "mosquito net", "table": "table", "chaise": "chair",
  "tabouret": "stool", "banc": "bench", "étagère": "shelf", "armoire": "wardrobe", "rideau": "curtain", "tapis": "carpet",
  "miroir": "mirror", "lampe": "lamp", "bougie": "candle", "allumette": "match", "briquet": "lighter", "torche": "torch",
  "marmite": "pot", "casserole": "saucepan", "poêle": "frying pan", "calebasse": "calabash", "assiette": "plate",
  "bol": "bowl", "tasse": "cup", "verre": "glass", "bouteille": "bottle", "cuillère": "spoon", "fourchette": "fork",
  "couteau": "knife", "louche": "ladle", "passoire": "strainer", "seau": "bucket", "bassine": "basin", "cuvette": "basin",
  "arrosoir": "watering can", "balai": "broom", "éponge": "sponge", "savon": "soap", "serviette": "towel", "clé": "key",
  "serrure": "lock", "cadenas": "padlock", "échelle": "ladder", "brouette": "wheelbarrow", "panier": "basket",
  "corde": "rope", "ficelle": "string", "sac": "bag", "boîte": "box", "caisse": "crate", "houe": "hoe", "hache": "axe",
  "machette": "machete", "faucille": "sickle", "pelle": "shovel", "râteau": "rake", "pioche": "pickaxe", "marteau": "hammer",
  "scie": "saw", "clou": "nail", "vis": "screw", "tenaille": "pincers", "lime": "file", "meule": "grindstone",
  "enclume": "anvil", "aiguille": "needle", "fil": "thread", "ciseaux": "scissors", "filet": "net", "hameçon": "hook",
  "piège": "trap", "arc": "bow", "flèche": "arrow", "lance": "spear", "fusil": "rifle", "couteau de chasse": "hunting knife",
  "tambour": "drum", "flûte": "flute", "trompette": "trumpet", "cloche": "bell", "gong": "gong", "sifflet": "whistle",
  "instrument": "instrument", "outil": "tool", "machine": "machine", "roue": "wheel", "moteur": "engine", "essence": "petrol",
  "pile": "battery", "fil électrique": "electric wire", "ampoule": "bulb", "vélo": "bicycle", "bicyclette": "bicycle",
  "moto": "motorcycle", "voiture": "car", "camion": "truck", "bus": "bus", "taxi": "taxi", "charrette": "cart",
  "bateau": "boat", "pirogue": "canoe", "barque": "small boat", "avion": "plane", "train": "train", "gare": "station",
  "aéroport": "airport", "port": "port", "garage": "garage", "carburant": "fuel", "pneu": "tyre", "volant": "steering wheel",
  "route goudronnée": "tarred road", "habit": "garment", "vêtement": "clothing", "chemise": "shirt", "pantalon": "trousers",
  "robe": "dress", "jupe": "skirt", "veste": "jacket", "manteau": "coat", "pull": "sweater", "short": "shorts",
  "sous-vêtement": "underwear", "chaussette": "sock", "chaussure": "shoe", "sandale": "sandal", "botte": "boot",
  "pagne": "wrapper", "boubou": "boubou", "foulard": "headscarf", "écharpe": "scarf", "ceinture": "belt", "cravate": "tie",
  "chapeau": "hat", "casquette": "cap", "gant": "glove", "lunettes": "glasses", "montre": "watch", "bijou": "jewel",
  "bague": "ring", "bracelet": "bracelet", "collier": "necklace", "boucle d'oreille": "earring", "perle": "bead",
  "masque": "mask", "tissu": "fabric", "coton": "cotton", "laine": "wool", "cuir": "leather", "bouton": "button",
  "poche": "pocket", "couture": "sewing",
  // Couleurs
  "blanc": "white", "noir": "black", "rouge": "red", "vert": "green", "jaune": "yellow", "bleu": "blue", "gris": "grey",
  "marron": "brown", "brun": "brown", "rose": "pink", "violet": "purple", "doré": "golden", "argenté": "silvery",
  "clair": "light", "foncé": "dark", "couleur": "colour",
  // Temps
  "jour": "day", "nuit": "night", "matin": "morning", "midi": "noon", "après-midi": "afternoon", "soir": "evening",
  "aube": "dawn", "crépuscule": "dusk", "minuit": "midnight", "aujourd'hui": "today", "hier": "yesterday",
  "avant-hier": "the day before yesterday", "demain": "tomorrow", "après-demain": "the day after tomorrow",
  "semaine": "week", "mois": "month", "année": "year", "an": "year", "siècle": "century", "heure": "hour",
  "minute": "minute", "seconde": "second", "moment": "moment", "instant": "instant", "temps": "time", "époque": "era",
  "saison": "season", "printemps": "spring", "été": "summer", "automne": "autumn", "hiver": "winter",
  "saison sèche": "dry season", "saison des pluies": "rainy season", "lundi": "Monday", "mardi": "Tuesday",
  "mercredi": "Wednesday", "jeudi": "Thursday", "vendredi": "Friday", "samedi": "Saturday", "dimanche": "Sunday",
  "janvier": "January", "février": "February", "mars": "March", "avril": "April", "mai": "May", "juin": "June",
  "juillet": "July", "août": "August", "septembre": "September", "octobre": "October", "novembre": "November",
  "décembre": "December", "anniversaire": "birthday", "vacances": "holidays", "rendez-vous": "appointment",
  // Verbes
  "manger": "to eat", "boire": "to drink", "goûter": "to taste", "avaler": "to swallow", "mâcher": "to chew",
  "cuisiner": "to cook", "cuire": "to cook", "bouillir": "to boil", "frire": "to fry", "rôtir": "to roast",
  "griller": "to grill", "piler": "to pound", "moudre": "to grind", "mélanger": "to mix", "remuer": "to stir",
  "verser": "to pour", "remplir": "to fill", "vider": "to empty", "dormir": "to sleep", "se réveiller": "to wake up",
  "se lever": "to get up", "s'asseoir": "to sit down", "se coucher": "to lie down", "se reposer": "to rest",
  "rêver": "to dream", "marcher": "to walk", "courir": "to run", "sauter": "to jump", "grimper": "to climb",
  "monter": "to go up", "descendre": "to go down", "tomber": "to fall", "glisser": "to slide", "ramper": "to crawl",
  "voler": "to fly", "nager": "to swim", "plonger": "to dive", "venir": "to come", "aller": "to go", "partir": "to leave",
  "arriver": "to arrive", "entrer": "to enter", "sortir": "to go out", "revenir": "to come back", "rester": "to stay",
  "s'arrêter": "to stop", "avancer": "to move forward", "reculer": "to move back", "suivre": "to follow", "fuir": "to flee",
  "poursuivre": "to chase", "porter": "to carry", "prendre": "to take", "donner": "to give", "recevoir": "to receive",
  "tenir": "to hold", "lâcher": "to let go", "jeter": "to throw", "lancer": "to throw", "attraper": "to catch",
  "pousser": "to push", "tirer": "to pull", "soulever": "to lift", "poser": "to put down", "ouvrir": "to open",
  "fermer": "to close", "casser": "to break", "briser": "to shatter", "couper": "to cut", "déchirer": "to tear",
  "coudre": "to sew", "tisser": "to weave", "tresser": "to braid", "nouer": "to tie", "attacher": "to attach",
  "détacher": "to detach", "creuser": "to dig", "planter": "to plant", "semer": "to sow", "arroser": "to water",
  "désherber": "to weed", "cultiver": "to cultivate", "récolter": "to harvest", "cueillir": "to pick", "chasser": "to hunt",
  "pêcher": "to fish", "traire": "to milk", "élever": "to raise", "abattre": "to slaughter", "tuer": "to kill",
  "dépecer": "to skin", "construire": "to build", "bâtir": "to build", "réparer": "to repair", "détruire": "to destroy",
  "allumer": "to light", "éteindre": "to put out", "brûler": "to burn", "laver": "to wash", "nettoyer": "to clean",
  "balayer": "to sweep", "ranger": "to tidy", "essuyer": "to wipe", "frotter": "to rub", "gratter": "to scratch",
  "peindre": "to paint", "parler": "to speak", "dire": "to say", "raconter": "to tell", "expliquer": "to explain",
  "demander": "to ask", "répondre": "to answer", "appeler": "to call", "crier": "to shout", "chuchoter": "to whisper",
  "chanter": "to sing", "siffler": "to whistle", "écouter": "to listen", "entendre": "to hear", "voir": "to see",
  "regarder": "to watch", "montrer": "to show", "cacher": "to hide", "chercher": "to look for", "trouver": "to find",
  "perdre": "to lose", "compter": "to count", "lire": "to read", "écrire": "to write", "dessiner": "to draw",
  "apprendre": "to learn", "enseigner": "to teach", "comprendre": "to understand", "savoir": "to know", "connaître": "to know",
  "oublier": "to forget", "se souvenir": "to remember", "penser": "to think", "croire": "to believe", "douter": "to doubt",
  "espérer": "to hope", "craindre": "to fear", "vouloir": "to want", "pouvoir": "to be able to", "devoir": "to have to",
  "oser": "to dare", "essayer": "to try", "commencer": "to begin", "continuer": "to continue", "finir": "to finish",
  "réussir": "to succeed", "échouer": "to fail", "aimer": "to love", "détester": "to hate", "haïr": "to hate",
  "préférer": "to prefer", "rire": "to laugh", "sourire": "to smile", "pleurer": "to cry", "trembler": "to tremble",
  "travailler": "to work", "jouer": "to play", "danser": "to dance", "gagner": "to win", "acheter": "to buy",
  "vendre": "to sell", "payer": "to pay", "coûter": "to cost", "échanger": "to exchange", "partager": "to share",
  "prêter": "to lend", "emprunter": "to borrow", "rembourser": "to repay", "aider": "to help", "protéger": "to protect",
  "défendre": "to defend", "attaquer": "to attack", "se battre": "to fight", "saluer": "to greet", "remercier": "to thank",
  "pardonner": "to forgive", "punir": "to punish", "promettre": "to promise", "jurer": "to swear", "mentir": "to lie",
  "tromper": "to deceive", "guérir": "to heal", "soigner": "to treat", "grandir": "to grow", "vieillir": "to age",
  "naître": "to be born", "vivre": "to live", "mourir": "to die", "se marier": "to marry", "accoucher": "to give birth",
  "allaiter": "to breastfeed", "enterrer": "to bury", "prier": "to pray", "bénir": "to bless", "maudire": "to curse",
  "se baigner": "to bathe", "s'habiller": "to get dressed", "se coiffer": "to do one's hair", "se raser": "to shave",
  "sentir": "to smell", "toucher": "to touch", "peser": "to weigh", "mesurer": "to measure", "choisir": "to choose",
  "décider": "to decide", "ajouter": "to add", "enlever": "to remove", "changer": "to change",
  // Adjectifs
  "grand": "big", "petit": "small", "gros": "fat", "mince": "thin", "épais": "thick", "fin": "fine", "haut": "high",
  "bas": "low", "long": "long", "court": "short", "large": "wide", "étroit": "narrow", "profond": "deep", "plat": "flat",
  "rond": "round", "carré": "square", "pointu": "pointed", "lourd": "heavy", "léger": "light", "plein": "full",
  "vide": "empty", "doux": "soft", "rugueux": "rough", "lisse": "smooth", "dur": "hard", "mou": "soft", "solide": "solid",
  "fragile": "fragile", "chaud": "hot", "tiède": "lukewarm", "brûlant": "burning", "frais": "cool", "gelé": "frozen",
  "humide": "damp", "sec": "dry", "mouillé": "wet", "propre": "clean", "sale": "dirty", "sombre": "dark",
  "brillant": "shiny", "terne": "dull", "beau": "beautiful", "laid": "ugly", "joli": "pretty", "nouveau": "new",
  "ancien": "old", "usé": "worn", "pourri": "rotten", "cru": "raw", "cuit": "cooked", "amer": "bitter", "acide": "sour",
  "piquant": "spicy", "fade": "bland", "bon": "good", "mauvais": "bad", "meilleur": "better", "pire": "worse",
  "rapide": "fast", "lent": "slow", "fort": "strong", "faible": "weak", "puissant": "powerful", "riche": "rich",
  "pauvre": "poor", "cher": "expensive", "gratuit": "free", "facile": "easy", "difficile": "difficult", "possible": "possible",
  "impossible": "impossible", "utile": "useful", "inutile": "useless", "important": "important", "dangereux": "dangerous",
  "prudent": "careful", "sûr": "safe", "vrai": "true", "faux": "false", "juste": "fair", "égal": "equal",
  "différent": "different", "semblable": "similar", "même": "same", "seul": "alone", "entier": "whole", "cassé": "broken",
  "gentil": "kind", "méchant": "mean", "cruel": "cruel", "généreux": "generous", "avare": "stingy", "courageux": "brave",
  "peureux": "fearful", "honnête": "honest", "malhonnête": "dishonest", "paresseux": "lazy", "travailleur": "hardworking",
  "intelligent": "intelligent", "poli": "polite", "impoli": "rude", "calme": "calm", "bruyant": "noisy", "content": "happy",
  "triste": "sad", "gai": "cheerful", "fâché": "angry", "fatigué": "tired", "sain": "healthy", "blessé": "injured",
  "guéri": "healed", "vivant": "alive", "mort": "dead", "bien portant": "well", "silencieux": "silent", "célèbre": "famous",
  "connu": "known", "inconnu": "unknown", "libre": "free",
  // Pronoms et mots grammaticaux
  "je": "I", "tu": "you", "il": "he", "elle": "she", "on": "one", "nous": "we", "vous": "you", "ils": "they",
  "elles": "they", "moi": "me", "toi": "you", "lui": "him", "eux": "them", "oui": "yes", "non": "no", "peut-être": "maybe",
  "et": "and", "ou": "or", "car": "because", "donc": "so", "avec": "with", "sans": "without", "pour": "for",
  "contre": "against", "dans": "in", "sous": "under", "devant": "in front of", "derrière": "behind", "entre": "between",
  "vers": "towards", "chez": "at", "près": "near", "loin": "far", "ici": "here", "là": "there", "là-bas": "over there",
  "dedans": "inside", "dehors": "outside", "en haut": "up", "en bas": "down", "à côté": "beside", "au milieu": "in the middle",
  "qui": "who", "que": "that", "quoi": "what", "quand": "when", "comment": "how", "pourquoi": "why", "combien": "how much",
  "lequel": "which", "beaucoup": "a lot", "peu": "little", "assez": "enough", "trop": "too much", "plus": "more",
  "moins": "less", "tout": "all", "rien": "nothing", "quelque chose": "something", "quelqu'un": "someone", "chaque": "each",
  "plusieurs": "several", "aucun": "none", "toujours": "always", "jamais": "never", "souvent": "often", "parfois": "sometimes",
  "encore": "again", "déjà": "already", "bientôt": "soon", "maintenant": "now", "tôt": "early", "tard": "late",
  "vite": "quickly", "lentement": "slowly", "ensemble": "together", "seulement": "only", "aussi": "also", "très": "very",
  "vraiment": "really", "presque": "almost", "environ": "about", "surtout": "especially",
  // Abstraits, vie sociale
  "nom": "name", "mot": "word", "parole": "speech", "histoire": "story", "conte": "tale", "chanson": "song",
  "musique": "music", "danse": "dance", "fête": "celebration", "jeu": "game", "sport": "sport", "voyage": "journey",
  "travail": "work", "métier": "trade", "commerce": "trade", "marché": "market", "prix": "price", "dette": "debt",
  "impôt": "tax", "salaire": "wage", "cadeau": "gift", "héritage": "inheritance", "mariage": "marriage", "divorce": "divorce",
  "naissance": "birth", "baptême": "baptism", "funérailles": "funeral", "deuil": "mourning", "cérémonie": "ceremony",
  "rituel": "ritual", "offrande": "offering", "sacrifice": "sacrifice", "bénédiction": "blessing", "malédiction": "curse",
  "prière": "prayer", "foi": "faith", "religion": "religion", "croyance": "belief", "âme": "soul", "esprit": "spirit",
  "génie": "genie", "coutume": "custom", "tradition": "tradition", "culture": "culture", "loi": "law", "règle": "rule",
  "droit": "right", "justice": "justice", "injustice": "injustice", "faute": "fault", "crime": "crime",
  "punition": "punishment", "pardon": "forgiveness", "promesse": "promise", "serment": "oath", "accord": "agreement",
  "dispute": "quarrel", "bagarre": "brawl", "guerre": "war", "paix": "peace", "victoire": "victory", "défaite": "defeat",
  "réunion": "meeting", "assemblée": "assembly", "conseil": "council", "gouvernement": "government", "liberté": "freedom",
  "école": "school", "leçon": "lesson", "examen": "exam", "livre": "book", "cahier": "notebook", "stylo": "pen",
  "crayon": "pencil", "papier": "paper", "lettre": "letter", "journal": "newspaper", "nouvelle": "news", "secret": "secret",
  "mystère": "mystery", "idée": "idea", "pensée": "thought", "raison": "reason", "mémoire": "memory", "oubli": "oblivion",
  "rêve": "dream", "espoir": "hope", "courage": "courage", "peur": "fear", "honte": "shame", "orgueil": "pride",
  "respect": "respect", "honneur": "honour", "jalousie": "jealousy", "envie": "envy", "haine": "hatred", "amour": "love",
  "amitié": "friendship", "pitié": "pity", "bonté": "kindness", "méchanceté": "wickedness", "patience": "patience",
  "sagesse": "wisdom", "ignorance": "ignorance", "chance": "luck", "malchance": "bad luck", "destin": "fate",
  "richesse": "wealth", "pauvreté": "poverty", "misère": "misery", "bonheur": "happiness", "malheur": "misfortune",
  "souffrance": "suffering", "douleur": "pain", "plaisir": "pleasure", "joie": "joy", "colère": "anger", "tristesse": "sadness",
  "effort": "effort", "repos": "rest", "santé": "health", "maladie": "illness", "blessure": "wound", "remède": "remedy",
  "vie": "life", "force": "strength", "vérité": "truth", "mensonge": "lie", "danger": "danger", "sécurité": "safety",
  "besoin": "need", "sommeil": "sleep", "silence": "silence", "bruit": "noise", "odeur": "smell", "poids": "weight",
  "taille": "size", "forme": "shape", "nombre": "number", "quantité": "quantity", "moitié": "half", "morceau": "piece",
  "début": "beginning", "milieu": "middle", "gauche": "left", "droite": "right", "centre": "centre", "bord": "edge",
  // Lieux
  "village": "village", "ville": "town", "quartier": "neighbourhood", "pays": "country", "nation": "nation",
  "région": "region", "frontière": "border", "capitale": "capital", "rue": "street", "place": "square",
  "carrefour": "crossroads", "boutique": "shop", "magasin": "store", "usine": "factory", "ferme": "farm",
  "plantation": "plantation", "mine": "mine", "bureau": "office", "banque": "bank", "poste": "post office",
  "hôpital": "hospital", "clinique": "clinic", "pharmacie": "pharmacy", "collège": "secondary school",
  "université": "university", "église": "church", "mosquée": "mosque", "temple": "temple", "chapelle": "chapel",
  "prison": "prison", "tribunal": "court", "commissariat": "police station", "caserne": "barracks", "stade": "stadium",
  "terrain": "field", "cimetière": "cemetery", "gare routière": "bus station", "hôtel": "hotel", "restaurant": "restaurant",
  "bar": "bar", "puits public": "public well", "fontaine": "fountain", "carrière": "quarry",
  // Argent et technologie
  "monnaie": "currency", "pièce": "coin", "billet": "banknote", "carte": "card", "compte": "account",
  "téléphone": "telephone", "portable": "mobile phone", "ordinateur": "computer", "internet": "internet", "radio": "radio",
  "télévision": "television", "photo": "photo", "image": "picture", "vidéo": "video", "film": "film", "message": "message",
  "appel": "call", "numéro": "number", "mot de passe": "password", "électricité": "electricity", "batterie": "battery",
  "chargeur": "charger", "écran": "screen", "clavier": "keyboard", "horloge": "clock", "calendrier": "calendar",
  "clé usb": "USB drive", "réseau": "network", "application": "app",
  // Agriculture
  "semence": "seed", "plant": "seedling", "tige": "stem", "bourgeon": "bud", "pétale": "petal", "pollen": "pollen",
  "sève": "sap", "tronc": "trunk", "rameau": "twig", "haie": "hedge", "verger": "orchard", "potager": "vegetable garden",
  "rizière": "rice paddy", "récolte": "harvest", "moisson": "harvest", "grange": "barn", "grenier": "granary", "silo": "silo",
  "engrais": "fertiliser", "compost": "compost", "irrigation": "irrigation", "sillon": "furrow", "labour": "ploughing",
  "semis": "sowing", "cacao": "cocoa", "canne à sucre": "sugar cane", "palmier": "palm tree", "cocotier": "coconut tree",
  "bananier": "banana tree", "manguier": "mango tree", "avocatier": "avocado tree", "oranger": "orange tree",
  "citronnier": "lemon tree", "baobab": "baobab", "acacia": "acacia", "bambou": "bamboo", "roseau": "reed",
  "papyrus": "papyrus", "orchidée": "orchid", "tournesol": "sunflower", "cactus": "cactus", "épouvantail": "scarecrow",
  "faucheuse": "mower", "tracteur": "tractor", "charrue": "plough", "semoir": "seeder", "bétail": "cattle",
  "volaille": "poultry", "étable": "cowshed", "poulailler": "henhouse", "enclos": "pen", "pâturage": "pasture",
  "abreuvoir": "trough", "auge": "trough", "mangeoire": "manger", "ruche": "beehive", "cire": "wax",
  "élevage": "livestock farming", "pêcherie": "fishery", "vivier": "fish pond",
  // Corps (santé)
  "articulation": "joint", "cartilage": "cartilage", "moelle": "marrow", "tendon": "tendon", "artère": "artery",
  "diaphragme": "diaphragm", "rate": "spleen", "pancréas": "pancreas", "grossesse": "pregnancy", "accouchement": "childbirth",
  "toux": "cough", "rhume": "cold", "grippe": "flu", "paludisme": "malaria", "diarrhée": "diarrhoea",
  "vomissement": "vomiting", "plaie": "wound", "cicatrice": "scar", "brûlure": "burn", "fracture": "fracture",
  "entorse": "sprain", "vertige": "dizziness", "évanouissement": "fainting", "handicap": "disability", "vaccin": "vaccine",
  "piqûre": "injection", "comprimé": "tablet", "sirop": "syrup", "pommade": "ointment", "pansement": "dressing",
  "bandage": "bandage", "béquille": "crutch", "thermomètre": "thermometer", "ordonnance": "prescription", "hygiène": "hygiene",
  "microbe": "germ", "épidémie": "epidemic", "contagion": "contagion", "guérison": "recovery", "convalescence": "convalescence",
  "régime": "diet", "nutrition": "nutrition", "vitamine": "vitamin", "protéine": "protein", "allergie": "allergy",
  "démangeaison": "itch", "crampe": "cramp", "courbature": "ache", "insomnie": "insomnia",
  // Nourriture (extra)
  "recette": "recipe", "ingrédient": "ingredient", "portion": "portion", "ration": "ration", "provisions": "provisions",
  "réserve": "reserve", "épicerie": "grocery", "boulangerie": "bakery", "boucherie": "butcher's shop", "cantine": "canteen",
  "assaisonnement": "seasoning", "marinade": "marinade", "levure": "yeast", "croûte": "crust", "mie": "crumb",
  "sandwich": "sandwich", "brochette": "skewer", "grillade": "grilled meat", "friture": "fried food", "vapeur": "steam",
  "bouillon": "broth", "purée": "purée", "compote": "compote", "dessert": "dessert", "friandise": "treat", "bonbon": "sweet",
  "chocolat": "chocolate", "biscuit": "biscuit", "crêpe": "pancake", "omelette": "omelette", "salade de fruits": "fruit salad",
  // Maison / objets (extra)
  "meuble": "furniture", "commode": "chest of drawers", "buffet": "sideboard", "coffre": "chest", "malle": "trunk",
  "valise": "suitcase", "sacoche": "satchel", "porte-monnaie": "purse", "trousse": "pouch", "cartable": "schoolbag",
  "sac à dos": "backpack", "parapluie": "umbrella", "éventail": "fan", "ventilateur": "fan", "climatiseur": "air conditioner",
  "réfrigérateur": "refrigerator", "congélateur": "freezer", "cuisinière": "cooker", "four": "oven", "réchaud": "stove",
  "bouilloire": "kettle", "théière": "teapot", "cafetière": "coffee pot", "mortier": "mortar", "pilon": "pestle",
  "râpe": "grater", "presse": "press", "entonnoir": "funnel", "spatule": "spatula", "fouet": "whisk", "rouleau": "rolling pin",
  "cadre": "frame", "réveil": "alarm clock", "chaîne": "chain", "crochet": "hook", "poulie": "pulley", "levier": "lever",
  "ressort": "spring", "aimant": "magnet", "loupe": "magnifying glass", "jumelles": "binoculars", "boussole": "compass",
  "balance": "scales", "mètre": "tape measure", "niveau": "level", "équerre": "set square", "pinceau": "brush",
  "rouleau de peinture": "paint roller",
  // Météo
  "climat": "climate", "température": "temperature", "humidité": "humidity", "sécheresse": "drought", "inondation": "flood",
  "crue": "flood", "érosion": "erosion", "tremblement de terre": "earthquake", "volcan": "volcano", "lave": "lava",
  "avalanche": "avalanche", "canicule": "heatwave", "grêle": "hail", "givre": "frost", "verglas": "black ice",
  "bruine": "drizzle", "averse": "shower", "brise": "breeze", "bourrasque": "gust", "ouragan": "hurricane",
  "cyclone": "cyclone", "tornade": "tornado", "mousson": "monsoon", "raz-de-marée": "tidal wave",
  "saison froide": "cold season", "saison chaude": "hot season",
  // Société, économie, justice
  "citoyenneté": "citizenship", "élection": "election", "vote": "vote", "candidat": "candidate", "parti": "party",
  "démocratie": "democracy", "république": "republic", "royaume": "kingdom", "empire": "empire", "colonie": "colony",
  "indépendance": "independence", "révolution": "revolution", "manifestation": "demonstration", "grève": "strike",
  "syndicat": "union", "association": "association", "coopérative": "cooperative", "entreprise": "company", "société": "society",
  "atelier": "workshop", "chantier": "construction site", "projet": "project", "contrat": "contract", "facture": "invoice",
  "reçu": "receipt", "budget": "budget", "économie": "economy", "crédit": "credit", "prêt": "loan", "épargne": "savings",
  "intérêt": "interest", "bénéfice": "profit", "perte": "loss", "faillite": "bankruptcy", "chômage": "unemployment",
  "emploi": "job", "prime": "bonus", "retraite": "retirement", "pension": "pension", "assurance": "insurance", "taxe": "tax",
  "douane": "customs", "passeport": "passport", "visa": "visa", "carte d'identité": "identity card", "permis": "permit",
  "amende": "fine", "témoignage": "testimony", "plainte": "complaint", "procès": "trial", "verdict": "verdict",
  "peine": "sentence", "esclavage": "slavery", "égalité": "equality",
  // Éducation, science, langue, maths
  "alphabet": "alphabet", "syllabe": "syllable", "grammaire": "grammar", "vocabulaire": "vocabulary", "dictée": "dictation",
  "rédaction": "essay", "calcul": "arithmetic", "addition": "addition", "soustraction": "subtraction",
  "multiplication": "multiplication", "division": "division", "géométrie": "geometry", "globe": "globe", "planète": "planet",
  "univers": "universe", "science": "science", "expérience": "experiment", "découverte": "discovery", "invention": "invention",
  "technologie": "technology", "diplôme": "diploma", "certificat": "certificate", "note": "grade", "moyenne": "average",
  "classe": "class", "cours": "lesson", "récréation": "break", "exercice": "exercise", "compas": "compass", "gomme": "eraser",
  "taille-crayon": "pencil sharpener", "ardoise": "slate", "craie": "chalk", "tableau": "blackboard", "pupitre": "desk",
  "bibliothèque": "library", "encre": "ink", "règle graduée": "ruler", "traduction": "translation",
  "prononciation": "pronunciation", "accent": "accent", "voyelle": "vowel", "consonne": "consonant", "ton": "tone",
  "signe": "sign", "symbole": "symbol", "chiffre": "digit", "opération": "operation", "résultat": "result",
  "problème": "problem", "solution": "solution", "question": "question", "réponse": "answer",
  // Émotions
  "émotion": "emotion", "sentiment": "feeling", "humeur": "mood", "enthousiasme": "enthusiasm", "excitation": "excitement",
  "surprise": "surprise", "étonnement": "astonishment", "curiosité": "curiosity", "ennui": "boredom", "solitude": "loneliness",
  "nostalgie": "nostalgia", "regret": "regret", "remords": "remorse", "gêne": "embarrassment", "timidité": "shyness",
  "confiance": "confidence", "méfiance": "distrust", "inquiétude": "worry", "angoisse": "anguish", "panique": "panic",
  "terreur": "terror", "soulagement": "relief", "satisfaction": "satisfaction", "fierté": "pride", "gratitude": "gratitude",
  "compassion": "compassion", "tendresse": "tenderness", "affection": "affection", "passion": "passion", "désir": "desire",
  "espérance": "hope", "déception": "disappointment", "frustration": "frustration", "rancune": "resentment",
  "vengeance": "revenge", "mépris": "contempt", "dégoût": "disgust", "admiration": "admiration",
  "compréhension": "understanding", "tolérance": "tolerance", "indulgence": "leniency",
};

const DICT = Object.assign({}, NOMBRES, MOTS);

// ========================= PHRASES =========================================
// Deux niveaux : (1) phrases IDIOMATIQUES (salutations, questions courantes) traduites
// explicitement ; (2) familles RÉGULIÈRES (conjugaisons, déplacements, recherches)
// traduites par RÈGLES qui composent avec des sous-traductions (verbes, lieux, noms).
// Le traducteur GÉNÉRALISE : il traduit aussi toute nouvelle phrase du même moule.

const IDIOM = {
  "bonjour": "Hello", "bonsoir": "Good evening", "bonne nuit": "Good night", "bonne journée": "Have a good day",
  "bienvenue": "Welcome", "comment vas-tu ?": "How are you?", "comment allez-vous ?": "How are you?",
  "je vais bien": "I'm fine", "ça va bien": "I'm well", "ça va, merci": "I'm fine, thanks", "et toi ?": "And you?",
  "comment va la famille ?": "How is the family?", "la famille va bien": "The family is well",
  "comment t'appelles-tu ?": "What's your name?", "je m'appelle paul": "My name is Paul", "enchanté": "Nice to meet you",
  "merci": "Thank you", "merci beaucoup": "Thank you very much", "de rien": "You're welcome",
  "il n'y a pas de quoi": "Don't mention it", "s'il te plaît": "Please", "s'il vous plaît": "Please",
  "excuse-moi": "Excuse me", "excusez-moi": "Excuse me", "je suis désolé": "I'm sorry", "ce n'est pas grave": "It's all right",
  "au revoir": "Goodbye", "à bientôt": "See you soon", "à demain": "See you tomorrow", "à tout à l'heure": "See you later",
  "bon voyage": "Have a good trip", "bonne route": "Safe journey", "bon appétit": "Enjoy your meal", "bonne chance": "Good luck",
  "bon courage": "Stay strong", "félicitations": "Congratulations", "joyeux anniversaire": "Happy birthday",
  "bonne année": "Happy new year", "repose-toi bien": "Rest well", "voici mon ami": "This is my friend",
  "voici ma femme": "This is my wife", "c'est mon frère": "This is my brother", "c'est mon père": "This is my father",
  "je suis content de te voir": "I'm glad to see you", "ça fait longtemps": "It's been a long time", "tu me manques": "I miss you",
  "quel âge as-tu ?": "How old are you?", "j'ai vingt ans": "I'm twenty years old", "où habites-tu ?": "Where do you live?",
  "j'habite au village": "I live in the village", "je suis d'ici": "I'm from here", "je viens de loin": "I come from far away",
  "es-tu marié ?": "Are you married?", "j'ai trois enfants": "I have three children", "je ne sais pas": "I don't know",
  "je ne comprends pas": "I don't understand", "je comprends": "I understand", "j'ai compris": "I've understood",
  "parle lentement": "Speak slowly", "répète, s'il te plaît": "Please repeat", "que veux-tu dire ?": "What do you mean?",
  "comment dit-on cela ?": "How do you say that?", "que signifie ce mot ?": "What does this word mean?",
  "peux-tu m'expliquer ?": "Can you explain to me?", "je parle un peu le français": "I speak a little French",
  "je ne parle pas bien": "I don't speak well", "écris-le pour moi": "Write it for me", "comment ça s'écrit ?": "How is it spelled?",
  "dis-le encore une fois": "Say it once more", "où vas-tu ?": "Where are you going?", "je vais au marché": "I'm going to the market",
  "d'où viens-tu ?": "Where are you coming from?", "je viens du champ": "I'm coming from the field", "où est la route ?": "Where is the road?",
  "c'est loin ?": "Is it far?", "c'est tout près": "It's very close", "va tout droit": "Go straight ahead",
  "tourne à droite": "Turn right", "tourne à gauche": "Turn left", "attends-moi ici": "Wait for me here", "suis-moi": "Follow me",
  "nous sommes arrivés": "We have arrived", "dépêche-toi": "Hurry up", "ne cours pas": "Don't run", "fais attention": "Be careful",
  "je suis perdu": "I'm lost", "peux-tu me montrer le chemin ?": "Can you show me the way?", "montre-moi la maison": "Show me the house",
  "combien ça coûte ?": "How much does it cost?", "c'est trop cher": "It's too expensive", "baisse le prix": "Lower the price",
  "c'est bon marché": "It's cheap", "je vais l'acheter": "I'll buy it", "donne-moi deux": "Give me two",
  "je n'ai pas d'argent": "I don't have any money", "as-tu la monnaie ?": "Do you have change?", "voici ton argent": "Here is your money",
  "garde la monnaie": "Keep the change", "le marché est loin": "The market is far", "que vends-tu ?": "What are you selling?",
  "je cherche du riz": "I'm looking for rice", "as-tu des tomates ?": "Do you have tomatoes?", "c'est frais ?": "Is it fresh?",
  "emballe-le": "Wrap it up", "j'ai faim": "I'm hungry", "j'ai soif": "I'm thirsty", "donne-moi de l'eau": "Give me some water",
  "le repas est prêt": "The meal is ready", "viens manger": "Come and eat", "c'est délicieux": "It's delicious",
  "c'est très bon": "It's very good", "j'ai assez mangé": "I've eaten enough", "encore un peu, s'il te plaît": "A little more, please",
  "le plat est trop pimenté": "The dish is too spicy", "passe-moi le sel": "Pass me the salt", "fais chauffer l'eau": "Heat the water",
  "allume le feu": "Light the fire", "éteins la lampe": "Turn off the lamp", "ferme la porte": "Close the door",
  "ouvre la fenêtre": "Open the window", "balaie la cour": "Sweep the courtyard", "lave les assiettes": "Wash the plates",
  "la maison est propre": "The house is clean", "quelle heure est-il ?": "What time is it?", "il est midi": "It's noon",
  "il est tard": "It's late", "il est encore tôt": "It's still early", "il fait chaud aujourd'hui": "It's hot today",
  "il fait froid": "It's cold", "il pleut": "It's raining", "il va pleuvoir": "It's going to rain", "le soleil est fort": "The sun is strong",
  "le ciel est clair": "The sky is clear", "demain, je pars": "Tomorrow, I'm leaving", "reviens plus tard": "Come back later",
  "on se voit demain": "See you tomorrow", "c'est samedi": "It's Saturday", "le mois prochain": "Next month",
  "l'année dernière": "Last year", "je suis malade": "I'm sick", "j'ai mal à la tête": "I have a headache",
  "j'ai mal au ventre": "I have a stomachache", "j'ai de la fièvre": "I have a fever", "où est l'hôpital ?": "Where is the hospital?",
  "appelle le médecin": "Call the doctor", "prends ce médicament": "Take this medicine", "repose-toi": "Rest",
  "bois beaucoup d'eau": "Drink plenty of water", "je me sens mieux": "I feel better", "il est guéri": "He is cured",
  "fais attention à toi": "Take care of yourself", "ça fait mal": "It hurts", "où as-tu mal ?": "Where does it hurt?",
  "que fais-tu ?": "What are you doing?", "je travaille au champ": "I work in the field", "aide-moi, s'il te plaît": "Help me, please",
  "le travail est fini": "The work is finished", "nous avons beaucoup travaillé": "We have worked a lot", "c'est fatigant": "It's tiring",
  "prends du repos": "Get some rest", "reviens demain matin": "Come back tomorrow morning", "le champ est grand": "The field is big",
  "la récolte est bonne": "The harvest is good", "il faut planter maintenant": "We must plant now", "apporte la houe": "Bring the hoe",
  "je t'aime": "I love you", "je suis content": "I'm happy", "je suis triste": "I'm sad", "je suis fâché": "I'm angry",
  "n'aie pas peur": "Don't be afraid", "sois patient": "Be patient", "c'est bien": "It's good", "c'est mauvais": "It's bad",
  "c'est vrai": "It's true", "c'est faux": "It's false", "tu as raison": "You're right", "tu as tort": "You're wrong",
  "je suis d'accord": "I agree", "je refuse": "I refuse", "c'est possible": "It's possible", "c'est impossible": "It's impossible",
  "ne t'inquiète pas": "Don't worry", "tout va bien": "Everything is fine", "c'est fini": "It's over", "ça suffit": "That's enough",
  "bravo": "Well done", "quel dommage": "What a pity", "tant mieux": "So much the better", "tant pis": "Never mind",
  "viens ici": "Come here", "va là-bas": "Go over there", "assieds-toi": "Sit down", "lève-toi": "Stand up",
  "écoute-moi": "Listen to me", "regarde": "Look", "attends": "Wait", "arrête": "Stop", "donne-moi ça": "Give me that",
  "prends ceci": "Take this", "tiens": "Here you go", "aide-moi à porter": "Help me carry", "ne touche pas": "Don't touch",
  "laisse-moi": "Leave me alone", "parle plus fort": "Speak louder", "ferme les yeux": "Close your eyes",
  "ouvre la main": "Open your hand", "appelle-le": "Call him", "cherche-le": "Look for him", "rends-moi mon livre": "Give me back my book",
  "qui est-ce ?": "Who is it?", "qu'est-ce que c'est ?": "What is it?", "où est-il ?": "Where is he?",
  "quand reviens-tu ?": "When are you coming back?", "pourquoi pleures-tu ?": "Why are you crying?", "comment as-tu fait ?": "How did you do it?",
  "avec qui ?": "With whom?", "où sommes-nous ?": "Where are we?", "est-ce loin ?": "Is it far?", "es-tu prêt ?": "Are you ready?",
  "as-tu fini ?": "Have you finished?", "peux-tu venir ?": "Can you come?", "veux-tu manger ?": "Do you want to eat?",
  "est-ce que tu comprends ?": "Do you understand?", "as-tu bien dormi ?": "Did you sleep well?", "où sont les enfants ?": "Where are the children?",
  "qu'est-ce qui se passe ?": "What's going on?", "que veux-tu ?": "What do you want?", "le chef nous a convoqués": "The chief has summoned us",
  "la réunion aura lieu demain": "The meeting will take place tomorrow", "toute la famille est là": "The whole family is here",
  "les enfants jouent dehors": "The children are playing outside", "ma mère prépare le repas": "My mother is preparing the meal",
  "mon père est aux champs": "My father is in the fields", "le marché est plein de monde": "The market is full of people",
  "il y a beaucoup de bruit": "There is a lot of noise", "la fête commence ce soir": "The party starts tonight",
  "nous allons danser toute la nuit": "We're going to dance all night", "le tambour appelle au rassemblement": "The drum calls people together",
  "prends soin des enfants": "Take care of the children", "respecte les anciens": "Respect the elders", "salue ton grand-père": "Greet your grandfather",
  "n'oublie pas de fermer la porte": "Don't forget to close the door", "rentre avant la nuit": "Come home before nightfall",
  "le voyage sera long": "The journey will be long", "la récolte a été abondante": "The harvest was plentiful",
  "il n'a pas plu depuis longtemps": "It hasn't rained for a long time", "l'eau est loin": "The water is far",
  "il faut puiser de l'eau": "We must fetch water", "le feu est éteint": "The fire has gone out", "rallume le feu": "Relight the fire",
  "la nuit tombe": "Night is falling", "le coq a chanté": "The rooster has crowed", "le soleil se lève": "The sun is rising",
  "les oiseaux chantent": "The birds are singing", "la lune est pleine": "The moon is full", "je pars à l'aube": "I leave at dawn",
  "je reviendrai à la saison des pluies": "I'll come back in the rainy season", "attends la fin de la pluie": "Wait for the rain to stop",
  "le chemin est glissant": "The path is slippery", "fais attention aux serpents": "Watch out for snakes", "le pont est cassé": "The bridge is broken",
  "nous traverserons la rivière": "We will cross the river", "le poisson est frais": "The fish is fresh", "la chasse a été bonne": "The hunt was good",
  "garde-moi une part": "Save me a share", "partageons le repas": "Let's share the meal", "l'hospitalité est sacrée": "Hospitality is sacred",
  "un étranger est arrivé au village": "A stranger has arrived in the village", "accueille-le comme il se doit": "Welcome him properly",
  "la patience est une vertu": "Patience is a virtue", "l'union fait la force": "Unity is strength", "le temps, c'est de l'argent": "Time is money",
  "petit à petit, l'oiseau fait son nid": "Little by little, the bird builds its nest", "il vaut mieux tard que jamais": "Better late than never",
  "chaque chose en son temps": "Everything in its own time", "on récolte ce que l'on sème": "You reap what you sow",
};

// Familles RÉGULIÈRES : arguments (verbes à l'infinitif, lieux, noms) traduits une fois.
const INF = {
  "manger": "eat", "boire": "drink", "dormir": "sleep", "partir": "leave", "rester": "stay", "travailler": "work",
  "chanter": "sing", "danser": "dance", "jouer": "play", "marcher": "walk", "courir": "run", "cuisiner": "cook",
  "me reposer": "rest", "t'aider": "help you", "vous aider": "help you", "apprendre": "learn", "écouter": "listen",
  "comprendre": "understand", "revenir": "come back", "continuer": "continue", "commencer": "start", "essayer": "try",
  "attendre": "wait", "payer": "pay", "vendre": "sell", "acheter": "buy", "laver": "wash", "balayer": "sweep",
  "planter": "plant", "récolter": "harvest", "pêcher": "fish", "chasser": "hunt", "lire": "read", "écrire": "write",
  "prier": "pray", "me laver": "wash up", "me préparer": "get ready", "y aller": "go there", "me lever": "get up",
  "me coucher": "lie down", "t'écouter": "listen to you", "t'expliquer": "explain to you", "t'accompagner": "come with you",
  "te suivre": "follow you", "me souvenir": "remember", "réfléchir": "think", "me dépêcher": "hurry", "rentrer": "go home",
  "sortir": "go out", "voyager": "travel", "me marier": "get married", "construire une maison": "build a house",
  "cultiver le champ": "farm the field", "vendre au marché": "sell at the market", "puiser l'eau": "fetch water",
  "faire la cuisine": "do the cooking", "garder les enfants": "look after the children", "traire les vaches": "milk the cows",
  "couper du bois": "chop wood", "aller à l'école": "go to school", "me reposer un peu": "rest a little",
  "changer d'avis": "change my mind", "recommencer": "start again",
};
const PLACE = {
  "au marché": "to the market", "au champ": "to the field", "au village": "to the village", "à la maison": "home",
  "à la rivière": "to the river", "à l'école": "to school", "à l'église": "to church", "à la fête": "to the party",
  "en ville": "to town", "chez le chef": "to the chief's", "chez le médecin": "to the doctor's", "à la ferme": "to the farm",
  "au puits": "to the well", "à la boutique": "to the shop", "au travail": "to work", "à la réunion": "to the meeting",
  "chez mes parents": "to my parents'", "à la cérémonie": "to the ceremony", "à l'hôpital": "to the hospital",
  "à la gare": "to the station", "au bureau": "to the office", "à la mosquée": "to the mosque", "au stade": "to the stadium",
  "à la plantation": "to the plantation", "chez le voisin": "to the neighbour's", "à la maison du chef": "to the chief's house",
  "à la fontaine": "to the fountain", "au bord de l'eau": "to the waterside", "au jardin": "to the garden",
  "dans la forêt": "into the forest",
};
const NOUN = {
  "le chef": "the chief", "le marché": "the market", "la rivière": "the river", "l'eau": "the water", "la nourriture": "the food",
  "mon père": "my father", "ma mère": "my mother", "mon ami": "my friend", "la maison": "the house", "le chemin": "the way",
  "l'enfant": "the child", "le médecin": "the doctor", "la route": "the road", "le village": "the village", "le champ": "the field",
  "le repas": "the meal", "la clé": "the key", "le livre": "the book", "la porte": "the door", "le feu": "the fire",
  "la lampe": "the lamp", "l'argent": "the money", "le chien": "the dog", "la marmite": "the pot", "mon frère": "my brother",
  "ma sœur": "my sister", "le maître": "the teacher", "le voisin": "the neighbour", "la boutique": "the shop", "le puits": "the well",
  "le tambour": "the drum", "la houe": "the hoe", "le panier": "the basket", "la calebasse": "the calabash", "le couteau": "the knife",
  "le troupeau": "the herd", "la récolte": "the harvest", "le tabouret": "the stool", "la natte": "the mat", "le sac": "the bag",
  "la corde": "the rope", "le message": "the message", "le téléphone": "the phone",
};

const cap = (s) => s ? s.charAt(0).toUpperCase() + s.slice(1) : s;

// Règles : chaque entrée = [préfixe, map, gabarit(arg) → EN]. L'ordre gère les
// familles qui partagent un préfixe (« je vais » : lieu OU verbe).
const RULES = [
  ["je ne veux pas ", INF, (a) => "I don't want to " + a],
  ["je veux ", INF, (a) => "I want to " + a],
  ["je peux ", INF, (a) => "I can " + a],
  ["il faut ", INF, (a) => "I must " + a],
  ["j'aime ", INF, (a) => "I like to " + a],
  ["nous allons ", PLACE, (a) => "we're going " + a],
  ["nous allons ", INF, (a) => "we're going to " + a],
  ["je vais ", PLACE, (a) => "I'm going " + a],
  ["je vais ", INF, (a) => "I'm going to " + a],
  ["il va ", PLACE, (a) => "he's going " + a],
  ["elle va ", PLACE, (a) => "she's going " + a],
  ["je reviens ", PLACE, (a) => "I'm coming back " + a],
  ["où est ", NOUN, (a) => "where is " + a + "?", true],
  ["je cherche ", NOUN, (a) => "I'm looking for " + a],
  ["as-tu vu ", NOUN, (a) => "have you seen " + a + "?", true],
  ["voici ", NOUN, (a) => "here is " + a],
  ["regarde ", NOUN, (a) => "look at " + a],
  ["je ne trouve pas ", NOUN, (a) => "I can't find " + a],
  ["donne-moi ", NOUN, (a) => "give me " + a],
  ["apporte ", NOUN, (a) => "bring " + a],
  ["peux-tu ", INF, (a) => "can you " + a + "?", true],
  ["vas-tu ", PLACE, (a) => "are you going " + a + "?", true],
];

/** Traduit une PHRASE française en anglais (idiome exact, sinon règle de pattern). null sinon. */
function phraseEn(s) {
  let low = s.trim().toLowerCase();
  if (Object.prototype.hasOwnProperty.call(IDIOM, low)) return IDIOM[low];
  const isQ = low.endsWith("?");
  const body = isQ ? low.replace(/\s*\?\s*$/, "") : low;   // « peux-tu manger ? » → « peux-tu manger »
  for (const [prefix, map, tpl, question] of RULES) {
    if (question && !isQ) continue;
    const src = question ? body : low;
    if (src.startsWith(prefix)) {
      const arg = src.slice(prefix.length).trim();
      if (Object.prototype.hasOwnProperty.call(map, arg)) return cap(tpl(map[arg]));
    }
  }
  return null;
}

/** Équivalent ANGLAIS d'un item source français (lettre, chiffre, mot OU phrase), ou null. */
export function sourceEn(fr) {
  if (fr == null) return null;
  const s = String(fr).trim();
  if (!s) return null;
  if (/^[A-Za-z]$/.test(s)) return s.toUpperCase();          // lettres isolées : identiques
  if (!/\p{L}/u.test(s)) return s;                            // chiffres/ponctuation seuls : identiques
  const k = s.toLowerCase();
  if (Object.prototype.hasOwnProperty.call(DICT, k)) return DICT[k];   // nombres + mots
  return phraseEn(s);                                        // phrases (idiomes + patterns)
}

/** Nombre de mots/nombres couverts (diagnostic / tests). */
export function sourceEnCount() { return Object.keys(DICT).length; }
