// Contenu du popup de remerciement affiché quand une contribution vient d'être CONFIRMÉE en
// base (pas au simple enregistrement local : au moment où le serveur l'a reçue). Le message et
// le visuel varient (1re contribution / palier / envoi courant, pool tourné au hasard) pour ne
// jamais répéter deux fois la même chose et pour porter la voix héritage/transmission/
// apprentissage. Module pur, sans dépendance au DOM, testable indépendamment de l'UI.
//
// Paliers RÉGULIERS et RAPPROCHÉS (tous les 5, Brice 2026-07-24) plutôt que rares et espacés :
// la régularité fait sentir à l'utilisateur qu'il compte, tout de suite et souvent, pas
// seulement à de grandes étapes lointaines. Pour que cette fréquence ne devienne jamais
// mécanique, chaque palier tire à la fois un TEXTE et un HABILLAGE visuel (« skin » — couleurs,
// halo, médaille) parmi un pool large, indépendamment l'un de l'autre : la combinatoire rend la
// répétition improbable à l'œil, même si le nombre de messages est fini.
//
// Auteur : Brice Kengni Zanguim.

function ip(s, ctx) {
  let o = s || "";
  for (const k in (ctx || {})) o = o.split("{" + k + "}").join(String(ctx[k]));
  return o;
}
function pick(pool) { return pool[Math.floor(Math.random() * pool.length)]; }

const FIRST = {
  fr: { title: "Ta toute première contribution", body: "Elle est enregistrée pour de bon dans la base : un mot de ta langue qui ne se perdra plus. Merci d'avoir fait ce premier pas." },
  en: { title: "Your very first contribution", body: "It's now safely stored in the archive: one more word of your language that won't be lost. Thank you for taking this first step." },
};

// Habillage visuel (couleurs du médaillon + halo derrière lui) : tourné au hasard, INDÉPENDAMMENT
// du texte, sur les paliers ET les envois courants. Palette FIXE (pas theme-dépendante), comme
// --nav-gold ailleurs dans l'app : un médaillon reste le même bijou en clair comme en sombre.
const SKINS = ["or", "argent", "bronze", "amethyste", "cuivre", "onyx", "ivoire"];
function pickSkin() { return pick(SKINS); }

// Paliers : un moment un peu plus marqué que les envois courants, TOUS LES 5 (régularité voulue).
export function isMilestoneCount(n) { return n > 0 && n % 5 === 0; }

const MILESTONE_MSG = {
  fr: [
    { title: "{n} contributions franchies", body: "Chaque mot que tu donnes est une pierre de plus dans la mémoire de ta langue. Continue, c'est un vrai trésor que tu bâtis." },
    { title: "Cap des {n} atteint", body: "Ce que tu transmets aujourd'hui, quelqu'un l'apprendra demain. Merci pour cette régularité." },
    { title: "{n} contributions, merci", body: "Peu de gens donnent autant de leur temps pour que leur langue reste vivante. La communauté te le doit." },
    { title: "{n}, et ça continue", body: "Un chiffre de plus, mais surtout une preuve : tu tiens la distance, et ta langue en sort grandie." },
    { title: "{n} pas de plus", body: "Chaque palier que tu franchis rapproche un peu plus ta langue d'un vrai dictionnaire vivant." },
    { title: "{n} fois merci", body: "Littéralement : {n} fois où tu as choisi de donner un peu de ton temps à ta langue. Ça se voit, et ça compte." },
    { title: "{n} contributions bien réelles", body: "Rien d'automatique là-dedans : {n} choix délibérés de transmettre. Continue, tu es sur une belle lancée." },
    { title: "Palier des {n}", body: "Ce que tu construis mot après mot ne s'effacera pas. Merci de continuer, régulièrement, sans bruit." },
  ],
  en: [
    { title: "{n} contributions reached", body: "Every word you give is one more stone in your language's memory. Keep going, you're building a real treasure." },
    { title: "{n}-contribution milestone", body: "What you pass on today, someone will learn tomorrow. Thank you for this steady work." },
    { title: "{n} contributions, thank you", body: "Few people give this much of their time to keep their language alive. The community owes you for it." },
    { title: "{n}, and counting", body: "One more number, but mostly proof: you're staying the course, and your language is better for it." },
    { title: "{n} steps further", body: "Every milestone you cross brings your language a little closer to a real, living dictionary." },
    { title: "{n} times, thank you", body: "Literally: {n} times you chose to give a bit of your time to your language. It shows, and it matters." },
    { title: "{n} very real contributions", body: "Nothing automatic here: {n} deliberate choices to pass something on. Keep this streak going." },
    { title: "Milestone: {n}", body: "What you're building word by word won't fade away. Thank you for keeping at it, quietly, regularly." },
  ],
};

// Pool ÉLARGI (2026-07-27, Brice : au moins 120 phrases très différentes, distinctes, mais qui
// oeuvrent toutes vers le même objectif) : 140 messages par langue, écrits à la main un par un
// (pas de gabarit combinatoire) pour que la variété se sente naturelle et jamais mécanique, même
// après des dizaines d'envois. Chaque message porte, à sa façon, un des 3 piliers (héritage/
// transmission/apprentissage) et cherche à transmettre une gratitude sincère, une reconnaissance
// réelle de l'effort et du temps donnés, jamais une formule creuse répétée.
const REGULAR = {
  fr: [
    { icon: "🌿", title: "Contribution enregistrée", body: "Un fragment de plus de ton héritage, gardé pour de bon dans la base." },
    { icon: "✨", title: "Merci pour ce mot", body: "Il fera peut-être partie de ce qu'apprendra un enfant, demain." },
    { icon: "🤝", title: "Envoyée et confirmée", body: "Ta langue avance d'un mot grâce à toi." },
    { icon: "🌍", title: "Bien reçu", body: "Ce que tu transmets aujourd'hui ne se perdra plus jamais." },
    { icon: "🔥", title: "Ça compte vraiment", body: "Continue, chaque contribution a de la valeur pour la communauté." },
    { icon: "🌾", title: "En sécurité dans la base", body: "Merci de semer aujourd'hui pour les générations à venir." },
    { icon: "🎁", title: "Un cadeau de plus", body: "C'est exactement ça, un héritage : merci de l'agrandir un peu." },
    { icon: "🌱", title: "Ça pousse", body: "Un mot de plus, une racine de plus. Ta langue grandit un peu grâce à toi aujourd'hui." },
    { icon: "🕊️", title: "Transmis", body: "C'est fait, c'est gardé, et ça voyagera jusqu'à quelqu'un qui en avait besoin." },
    { icon: "💛", title: "Sincèrement merci", body: "Pas un message automatique : un vrai merci, pour le temps que tu viens de donner." },
    { icon: "📜", title: "Un mot de plus dans l'histoire", body: "Ce que tu viens d'écrire ou de dire rejoint une mémoire qui ne s'effacera pas." },
    { icon: "🌙", title: "Merci, vraiment", body: "Tu as pris un instant de ta journée pour ta langue. Ça ne passe pas inaperçu." },
    { icon: "🧡", title: "Ton geste compte", body: "Peu de gens prennent le temps de faire ce que tu viens de faire. Merci." },
    { icon: "🗝️", title: "Une clé de plus", body: "Chaque mot que tu laisses ouvre la langue un peu plus à celles et ceux qui viendront." },
    { icon: "🌳", title: "Une branche de plus", body: "Ta langue grandit, feuille après feuille, et tu en es une des racines." },
    { icon: "☀️", title: "Merci d'avoir pris ce temps", body: "Ce moment que tu viens de donner ne sera jamais perdu, il est déjà en sécurité." },
    { icon: "🪶", title: "Une plume légère, un poids réel", body: "Ça semble un petit geste. C'est en réalité un vrai morceau de mémoire sauvé." },
    { icon: "🌟", title: "Tu comptes pour ta langue", body: "Sans des gens comme toi, elle resterait silencieuse. Merci de lui donner de la voix." },
    { icon: "🫶", title: "Reçu avec gratitude", body: "Ce que tu viens de partager sera utile à quelqu'un que tu ne rencontreras peut-être jamais." },
    { icon: "🧵", title: "Un fil de plus", body: "Tu tisses, mot après mot, le lien entre ceux qui savent et ceux qui apprendront." },
    { icon: "🏺", title: "Gardé comme un trésor", body: "Ta contribution rejoint celles de toute une communauté qui refuse d'oublier." },
    { icon: "🕯️", title: "Une lumière de plus", body: "Chaque mot que tu donnes éclaire un peu plus le chemin de ceux qui suivront." },
    { icon: "🌤️", title: "Belle initiative", body: "Tu n'as rien attendu en retour, et pourtant ça change vraiment quelque chose." },
    { icon: "🎶", title: "Une note ajoutée", body: "Ta langue est une mélodie collective, et tu viens d'y ajouter la tienne." },
    { icon: "🤲", title: "Offert avec soin", body: "On sent le soin que tu as mis, et ça se voit. Merci pour ce cadeau." },
    { icon: "🌊", title: "Une vague qui porte loin", body: "Ce mot que tu viens de donner peut voyager bien plus loin que tu ne l'imagines." },
    { icon: "🧭", title: "Un repère de plus", body: "Grâce à toi, quelqu'un saura un jour comment dire ce mot dans ta langue." },
    { icon: "🔔", title: "Ça résonne", body: "Ta contribution ne reste pas silencieuse : elle rejoint une bibliothèque vivante, consultée par d'autres." },
    { icon: "🪘", title: "Le rythme continue", body: "Ta langue avance à ton rythme, et chaque contribution la fait vivre un peu plus." },
    { icon: "🌸", title: "Une fleur de plus au jardin", body: "Ta langue est un jardin collectif. Merci d'y avoir planté quelque chose aujourd'hui." },
    { icon: "📖", title: "Une page qui ne se refermera pas", body: "Ce que tu viens d'écrire restera lisible, consultable, utile, pour longtemps." },
    { icon: "🧶", title: "Un nœud de plus, solide", body: "Chaque contribution resserre le lien entre les générations de ta langue." },
    { icon: "🌾", title: "Merci pour ce grain", body: "Un grain de plus dans la moisson commune. Ce n'est jamais rien." },
    { icon: "🕰️", title: "Ça traversera le temps", body: "Ce que tu viens de donner sera encore là dans dix ans, dans cent ans peut-être." },
    { icon: "💎", title: "Une petite pierre précieuse", body: "Chaque contribution est modeste en apparence, précieuse en réalité." },
    { icon: "🐾", title: "Une trace qui reste", body: "Tu viens de laisser une empreinte durable dans la mémoire de ta langue." },
    { icon: "🎈", title: "Ça s'envole, mais ça reste", body: "Ta voix ou ton mot rejoint la base pour de bon, mais son utilité, elle, n'a pas de limite." },
    { icon: "🍃", title: "Ça circule déjà", body: "Ce que tu viens de partager peut désormais être entendu, lu, appris, par n'importe qui." },
    { icon: "🧑‍🤝‍🧑", title: "Toute une communauté te dit merci", body: "Ce que tu fais seul profite à beaucoup d'autres. C'est ça, la force du collectif." },
    { icon: "🪄", title: "Un petit geste, un vrai effet", body: "Ce n'était peut-être qu'une minute pour toi. C'est un mot de plus pour toujours." },
    { icon: "🌻", title: "Merci de faire fleurir ta langue", body: "Elle a besoin de gens comme toi pour continuer d'exister pleinement." },
    { icon: "🧊", title: "Rien ne fond, tout reste", body: "Contrairement à la mémoire, ce que tu viens d'écrire ne s'efface jamais." },
    { icon: "🐦", title: "Un mot qui s'envole loin", body: "Il peut désormais être entendu par quelqu'un à l'autre bout du monde." },
    { icon: "🌈", title: "Merci pour cette couleur de plus", body: "Chaque contribution ajoute un peu plus de richesse à ce que devient ta langue." },
    { icon: "🧺", title: "Récolté avec soin", body: "Ce que tu viens de donner rejoint une récolte patiente, construite mot après mot." },
    { icon: "🕊️", title: "Ça vole déjà plus loin que toi", body: "Ta contribution appartient désormais à tout le monde, pour toujours." },
    { icon: "🌺", title: "Reconnaissance sincère", body: "On ne te remercie pas assez souvent pour ce genre de geste. Alors : merci." },
    { icon: "🌤️", title: "Un rayon de plus", body: "Ta contribution ajoute un peu de lumière à un travail collectif immense." },
    { icon: "🧑‍🌾", title: "Merci d'avoir semé", body: "Quelqu'un d'autre récoltera un jour ce que tu viens de planter." },
    { icon: "🏮", title: "Une lanterne allumée", body: "Ce que tu transmets aujourd'hui éclairera le chemin de quelqu'un demain." },
    { icon: "🎼", title: "Une phrase ajoutée à la partition", body: "Ta langue s'écrit à plusieurs voix, et la tienne compte vraiment." },
    { icon: "🧩", title: "Une pièce de plus au puzzle", body: "Ta langue se reconstitue, morceau après morceau, grâce à des gestes comme le tien." },
    { icon: "🌕", title: "Merci pour ce que tu viens de faire", body: "C'est simple à dire, mais sincère : ce que tu fais a une vraie valeur." },
    { icon: "🐚", title: "Un écho qui portera loin", body: "Ce mot résonnera bien après toi, pour quelqu'un que tu ne connaîtras jamais." },
    { icon: "🧭", title: "Tu montres le chemin", body: "Grâce à des gestes comme celui-ci, ta langue reste accessible à qui veut l'apprendre." },
    { icon: "🌷", title: "Merci d'y avoir pensé", body: "Beaucoup remettent à plus tard. Toi, tu viens de le faire. Merci." },
    { icon: "🪵", title: "Une bûche de plus au feu", body: "Ta contribution garde vivante une flamme que personne ne veut voir s'éteindre." },
    { icon: "🌀", title: "Ça part loin, ça reste proche", body: "Ta voix rejoint celles de toute une communauté, et elle garde toute sa place." },
    { icon: "🧡", title: "On le remarque", body: "Chaque contribution est comptée, gardée, utile. La tienne aussi, dès maintenant." },
    { icon: "🕸️", title: "Un lien de plus dans le tissu", body: "Ta langue se tisse de milliers de petits gestes comme celui-là. Merci d'en faire partie." },
    { icon: "🌌", title: "Une étoile de plus", body: "Prise seule, elle semble petite. Avec toutes les autres, elle éclaire un ciel entier." },
    { icon: "🍂", title: "Rien ne tombe dans l'oubli", body: "Ce que tu viens de donner ne suivra pas le sort des feuilles mortes : il reste, lui." },
    { icon: "🧑‍🍼", title: "Pour les générations à venir", body: "Un enfant qui n'est pas encore né apprendra peut-être ce mot grâce à toi." },
    { icon: "🪴", title: "Merci d'arroser ce projet", body: "Une langue vivante a besoin d'attention régulière. Tu viens de lui en donner." },
    { icon: "🎋", title: "Une pousse de plus", body: "Chaque contribution fait grandir un peu plus ce qui, un jour, sera un vrai dictionnaire vivant." },
    { icon: "🧊", title: "Conservé, pas figé", body: "Ce que tu viens de dire ou d'écrire reste vivant, consultable, utile à qui en a besoin." },
    { icon: "🏹", title: "Ça touche loin", body: "Un mot donné aujourd'hui peut être découvert par quelqu'un dans très longtemps." },
    { icon: "🌬️", title: "Ta voix porte", body: "Elle voyage désormais au-delà de cette page, jusqu'à d'autres oreilles." },
    { icon: "🪞", title: "Un reflet fidèle de ta langue", body: "Ce que tu viens de donner est authentique, et c'est exactement ce qui compte." },
    { icon: "🧑‍🏫", title: "Tu transmets, comme un maître le ferait", body: "Ce geste simple est en réalité un acte de transmission, au sens le plus fort du mot." },
    { icon: "🎇", title: "Une étincelle de plus", body: "Elle peut sembler discrète. Multipliée par des centaines d'autres, elle devient un feu." },
    { icon: "🧑‍🎨", title: "Tu façonnes quelque chose de durable", body: "Ta langue se construit aussi comme une œuvre collective, un mot à la fois." },
    { icon: "🌒", title: "Merci pour cet instant donné", body: "Tu aurais pu faire autre chose. Tu as choisi ta langue. Ça se remarque." },
    { icon: "🧑‍🤝‍🧑", title: "Une chaîne humaine, un maillon de plus", body: "Avant toi, d'autres ont transmis. Après toi, d'autres apprendront. Tu es entre les deux, et ça compte." },
    { icon: "🌾", title: "Chaque grain compte pour la moisson", body: "Une base solide se construit ainsi : geste après geste, mot après mot." },
    { icon: "🕯️", title: "Une flamme qu'on protège", body: "Ta langue ne s'éteindra pas tant que des gens comme toi continueront de la nourrir." },
    { icon: "🎁", title: "Un cadeau qu'on n'attendait pas", body: "Personne ne t'a obligé à faire ça. C'est précisément ce qui le rend précieux." },
    { icon: "🪷", title: "Ça s'épanouit doucement", body: "Ta langue ne grandit pas d'un coup, mais contribution après contribution. La tienne y participe pleinement." },
    { icon: "🧑‍🚀", title: "Tu vises loin, sans le savoir", body: "Ce mot que tu viens de laisser pourrait un jour aider une intelligence artificielle à mieux comprendre ta langue." },
    { icon: "🌗", title: "Merci pour ce petit pas", body: "Les petits pas, répétés, construisent les plus grands chemins. Le tien vient d'être posé." },
    { icon: "🧺", title: "Une main de plus dans la récolte", body: "Ce que tu viens d'apporter s'ajoute à celui de toute une communauté patiente et déterminée." },
    { icon: "🌤️", title: "Un mot qui a du poids", body: "Pas de formule creuse ici : ce que tu fais a un vrai poids pour ta langue et pour ceux qui la parleront demain." },
    { icon: "🪁", title: "Ça s'élève, porté par tous", body: "Ta contribution rejoint celles des autres et, ensemble, elles font vivre ta langue plus haut." },
    { icon: "🧑‍👩‍👧", title: "D'une génération à l'autre", body: "Ce que tu transmets aujourd'hui pourrait bien être ce qu'apprendra ton petit-enfant, un jour." },
    { icon: "🌼", title: "Un geste simple, un effet profond", body: "Tu ne le vois peut-être pas encore, mais ce que tu viens de faire compte vraiment." },
    { icon: "🧑‍🔬", title: "Une donnée précieuse pour la suite", body: "Ce mot enrichit un corpus qui servira aussi bien aux linguistes qu'aux futurs claviers de ta langue." },
    { icon: "🌅", title: "Un nouveau jour pour ta langue", body: "Chaque contribution repousse un peu plus loin le risque qu'elle soit un jour oubliée." },
    { icon: "🧑‍🎤", title: "Ta voix a de la valeur", body: "Elle porte un accent, un rythme, une musique que personne d'autre ne peut donner à ta place." },
    { icon: "🪢", title: "Un nœud qui tient bon", body: "Ce que tu viens de faire relie un peu plus solidement le passé de ta langue à son avenir." },
    { icon: "🌟", title: "Tu fais partie de l'histoire", body: "Dans quelques années, on pourra dire que des gens comme toi ont fait vivre cette langue." },
    { icon: "🧑‍🌾", title: "Merci pour cette récolte partagée", body: "Ce que tu donnes aujourd'hui nourrira la curiosité de quelqu'un, un jour." },
    { icon: "🕊️", title: "Libéré, transmis, gardé", body: "Ton mot n'appartient plus qu'à toi : il appartient maintenant à toute la communauté, pour toujours." },
    { icon: "🌤️", title: "Reconnu, apprécié", body: "Ce que tu viens de faire ne passe pas inaperçu, même si personne n'est là pour te voir le faire." },
    { icon: "🧑‍🏭", title: "Un artisan de plus", body: "Ta langue se construit à la main, contribution après contribution, et tu en es un des artisans." },
    { icon: "🌙", title: "Merci pour ce moment", body: "Que ce soit le matin, le soir ou en pleine nuit, ce moment que tu donnes à ta langue compte." },
    { icon: "🌾", title: "Ta part de la moisson", body: "Elle est petite prise seule, essentielle une fois réunie à toutes les autres." },
    { icon: "🧑‍🤝‍🧑", title: "Ensemble, on va plus loin", body: "Seul, ce mot resterait un mot. Avec les autres, il devient un dictionnaire vivant." },
    { icon: "🕯️", title: "Ça ne s'éteint pas", body: "Ce que tu viens de transmettre continuera d'exister bien après ce simple instant." },
    { icon: "🌱", title: "L'arbre qui pousse, doucement", body: "Une pousse fragile aujourd'hui. Avec le temps et les efforts de tous, elle deviendra un arbre." },
    { icon: "💫", title: "Merci, du fond du cœur", body: "Ce que tu viens de faire est petit à l'échelle d'une vie, immense à l'échelle d'une langue." },
    { icon: "🧑‍🎓", title: "Tu deviens un peu plus un gardien de ta langue", body: "Ce rôle ne s'improvise pas. Il se construit exactement comme tu viens de le faire." },
    { icon: "🌤️", title: "Ça ne demande rien en retour", body: "Et c'est précisément pour ça que ce que tu viens de donner a autant de valeur." },
    { icon: "🧑‍🦳", title: "Un pont vers les anciens", body: "Ce mot que tu viens de transmettre existait peut-être déjà dans la bouche de tes grands-parents." },
    { icon: "🌾", title: "Semé aujourd'hui, récolté demain", body: "Personne ne sait encore qui apprendra ce mot grâce à toi. C'est ça, la beauté du geste." },
    { icon: "🧑‍🚒", title: "Tu protèges quelque chose de fragile", body: "Une langue peut s'éteindre en silence. Grâce à toi, celle-ci résiste un peu plus." },
    { icon: "🌻", title: "Ça fleurit grâce à toi", body: "Ta langue a besoin d'attention constante, et tu viens de lui en offrir." },
    { icon: "🧑‍🎨", title: "Une touche de plus au tableau", body: "Ta langue se peint collectivement, et ta contribution y ajoute une vraie couleur." },
    { icon: "🕰️", title: "Le temps ne l'effacera pas", body: "Contrairement à tant de choses, ce que tu viens de laisser va durer." },
    { icon: "🌗", title: "Un petit pas, un grand sens", body: "Vu de loin, ce n'est qu'un mot. Vu de près, c'est un acte de fidélité à ta langue." },
    { icon: "🧑‍🤝‍🧑", title: "Ta générosité en dit long", body: "Tu donnes ton temps sans qu'on te le demande deux fois. Merci pour ça." },
    { icon: "🌈", title: "Ta langue s'enrichit d'une nuance de plus", body: "Chaque mot ajouté rend la palette un peu plus complète, un peu plus fidèle à ce qu'elle est vraiment." },
    { icon: "🧑‍🍳", title: "Une recette transmise", body: "Comme une recette de famille, ta langue se transmet de main en main. Merci d'y participer." },
    { icon: "🌍", title: "Un mot, une empreinte mondiale", body: "Il est désormais accessible depuis n'importe où dans le monde. Petit geste, portée immense." },
    { icon: "🧑‍⚕️", title: "Tu prends soin de ta langue", body: "Comme on prend soin d'un proche fragile, avec constance et attention. Merci." },
    { icon: "🌟", title: "Ce que tu fais est rare", body: "Beaucoup de langues du monde n'ont personne pour faire ce que tu viens de faire. Toi, tu l'as fait." },
    { icon: "🧑‍🏫", title: "Un enseignement silencieux", body: "Sans le savoir, tu viens peut-être d'apprendre quelque chose à quelqu'un que tu ne rencontreras jamais." },
    { icon: "🌙", title: "Même la nuit, ta langue avance", body: "Peu importe l'heure à laquelle tu contribues, ce que tu donnes compte exactement pareil." },
    { icon: "🧑‍🚀", title: "Tu écris un peu de l'avenir", body: "Ce mot pourrait faire partie des tout premiers outils numériques de ta langue." },
    { icon: "🌾", title: "Une moisson qui ne finit jamais", body: "Chaque contribution en appelle une autre, et la récolte continue de grandir." },
    { icon: "🧑‍🎤", title: "Ta voix ne ressemble à aucune autre", body: "Elle porte quelque chose que personne d'autre ne peut transmettre à ta place." },
    { icon: "🌤️", title: "Un instant, une trace durable", body: "Ce que tu viens de faire aura duré quelques secondes. Son effet, lui, durera bien plus longtemps." },
    { icon: "🧑‍🏭", title: "Bâtisseur, un mot à la fois", body: "Les grandes bibliothèques se construisent toujours ainsi : patiemment, contribution après contribution." },
    { icon: "🌺", title: "On ne t'oublie pas", body: "Ta contribution reste liée à toi, à ton nom si tu le souhaites, pour toujours." },
    { icon: "🕊️", title: "Un vol qui commence ici", body: "Ce mot part de toi et peut désormais atterrir n'importe où, chez n'importe qui." },
    { icon: "🧑‍🌾", title: "La terre se souvient de qui l'a cultivée", body: "Ta langue se souviendra, d'une certaine façon, de ce que tu viens d'y apporter." },
    { icon: "🌱", title: "Discret aujourd'hui, essentiel demain", body: "Ce que tu plantes maintenant deviendra peut-être une évidence pour les générations futures." },
    { icon: "🧑‍🎓", title: "Tu apprends en donnant", body: "En transmettant ce mot, tu consolides aussi ta propre relation à ta langue." },
    { icon: "🌤️", title: "Merci d'avoir choisi ta langue, aujourd'hui", body: "Parmi tout ce que tu aurais pu faire, tu as choisi ça. Ça compte énormément." },
    { icon: "🧑‍🤝‍🧑", title: "Un maillon qu'on ne voit pas toujours", body: "Mais sans lui, toute la chaîne de transmission serait plus fragile. Merci d'en être un." },
    { icon: "🌾", title: "Une graine qui ne demande rien", body: "Elle pousse en silence, sans réclamer d'attention. Comme ta contribution aujourd'hui." },
    { icon: "🕯️", title: "Tenir la flamme, ensemble", body: "Une langue vit tant que des gens continuent d'y contribuer. Tu viens de faire ta part." },
    { icon: "🌙", title: "Ce n'est jamais anodin", body: "Un mot de plus dans la base, c'est un mot de moins à risquer d'oublier un jour." },
    { icon: "🧑‍🎨", title: "Une œuvre à plusieurs mains", body: "Ta langue n'appartient à personne en particulier, elle appartient à tous ceux qui la font vivre. Toi y compris." },
    { icon: "🌤️", title: "Tu fais avancer quelque chose de plus grand que toi", body: "Un projet collectif, patient, qui dépasse largement cette seule contribution, mais qui a besoin d'elle." },
    { icon: "🧑‍🍼", title: "Un jour, quelqu'un dira merci", body: "Peut-être pas aujourd'hui, mais un jour, quelqu'un tombera sur ce mot et en sera reconnaissant." },
    { icon: "🌾", title: "Patiemment, sûrement", body: "Ta langue ne se construit pas d'un coup. Elle se construit ainsi, contribution après contribution, comme celle-ci." },
    { icon: "🧑‍🤝‍🧑", title: "Merci de faire partie de l'aventure", body: "Ce projet existe grâce à des gens comme toi, prêts à donner un peu de leur temps pour ta langue." },
    { icon: "🌟", title: "Une preuve de plus que ça compte", body: "Chaque nouvelle contribution confirme une chose : ta langue mérite d'être préservée, et tu y crois." },
    { icon: "🕊️", title: "Merci d'avoir donné de ta voix, ou de ton temps", body: "Les deux ont la même valeur ici : celle d'un geste sincère pour ta langue." },
    { icon: "💫", title: "Ce moment restera, même petit", body: "Toutes les grandes bibliothèques du monde ont commencé par un premier mot, puis un deuxième, comme celui-ci." },
  ],
  en: [
    { icon: "🌿", title: "Contribution saved", body: "One more piece of your heritage, kept for good in the archive." },
    { icon: "✨", title: "Thank you for this word", body: "It might become part of what a child learns, tomorrow." },
    { icon: "🤝", title: "Sent and confirmed", body: "Your language moves forward by one word, thanks to you." },
    { icon: "🌍", title: "Received", body: "What you share today will never be lost again." },
    { icon: "🔥", title: "It truly matters", body: "Keep going, every contribution has real value for the community." },
    { icon: "🌾", title: "Safely stored", body: "Thank you for planting today for the generations to come." },
    { icon: "🎁", title: "One more gift", body: "That's exactly what a heritage is: thank you for growing it a little more." },
    { icon: "🌱", title: "It's growing", body: "One more word, one more root. Your language grows a little today, because of you." },
    { icon: "🕊️", title: "Passed on", body: "It's done, it's kept, and it will travel all the way to someone who needed it." },
    { icon: "💛", title: "Sincerely, thank you", body: "Not an automated message: a real thank you, for the time you just gave." },
    { icon: "📜", title: "One more word in history", body: "What you just wrote or said joins a memory that won't fade away." },
    { icon: "🌙", title: "Truly, thank you", body: "You took a moment out of your day for your language. That doesn't go unnoticed." },
    { icon: "🧡", title: "Your gesture matters", body: "Few people take the time to do what you just did. Thank you." },
    { icon: "🗝️", title: "One more key", body: "Every word you leave opens your language a little wider to those who'll come after." },
    { icon: "🌳", title: "One more branch", body: "Your language grows, leaf by leaf, and you're one of its roots." },
    { icon: "☀️", title: "Thank you for taking this time", body: "This moment you just gave is already kept safe, forever." },
    { icon: "🪶", title: "Light as a feather, heavy with meaning", body: "It may seem like a small act. It's really a piece of memory just saved." },
    { icon: "🌟", title: "You matter to your language", body: "Without people like you, it would stay silent. Thank you for giving it a voice." },
    { icon: "🫶", title: "Received with gratitude", body: "What you just shared will be useful to someone you may never meet." },
    { icon: "🧵", title: "One more thread", body: "Word by word, you're weaving the link between those who know and those who'll learn." },
    { icon: "🏺", title: "Kept like a treasure", body: "Your contribution joins those of a whole community that refuses to forget." },
    { icon: "🕯️", title: "One more light", body: "Every word you give lights the path a little further for those who follow." },
    { icon: "🌤️", title: "A lovely thing to do", body: "You expected nothing in return, and yet it truly changes something." },
    { icon: "🎶", title: "One more note added", body: "Your language is a collective melody, and you just added your own." },
    { icon: "🤲", title: "Offered with care", body: "The care you put into this shows. Thank you for this gift." },
    { icon: "🌊", title: "A wave that travels far", body: "This word you just gave can travel much further than you imagine." },
    { icon: "🧭", title: "One more landmark", body: "Because of you, someone will one day know how to say this word in your language." },
    { icon: "🔔", title: "It resonates", body: "Your contribution doesn't stay silent: it joins a living library, consulted by others." },
    { icon: "🪘", title: "The rhythm goes on", body: "Your language moves forward at its own pace, and every contribution keeps it alive." },
    { icon: "🌸", title: "One more flower in the garden", body: "Your language is a shared garden. Thank you for planting something in it today." },
    { icon: "📖", title: "A page that won't close", body: "What you just wrote will stay readable, searchable, useful, for a long time." },
    { icon: "🧶", title: "One more knot, tightly tied", body: "Every contribution ties the generations of your language a little closer together." },
    { icon: "🌾", title: "Thank you for this grain", body: "One more grain in the shared harvest. It's never nothing." },
    { icon: "🕰️", title: "It will outlast time", body: "What you just gave will still be here in ten years, maybe a hundred." },
    { icon: "💎", title: "A small, precious stone", body: "Every contribution looks modest, and is precious in truth." },
    { icon: "🐾", title: "A trace that stays", body: "You just left a lasting mark on the memory of your language." },
    { icon: "🎈", title: "It rises, but it stays", body: "Your voice or your word now belongs to the archive for good, but its usefulness has no limit." },
    { icon: "🍃", title: "It's already moving", body: "What you just shared can now be heard, read, learned, by anyone." },
    { icon: "🧑‍🤝‍🧑", title: "A whole community thanks you", body: "What you do alone benefits many others. That's the strength of the collective." },
    { icon: "🪄", title: "A small act, a real effect", body: "It may have taken you a minute. It's one more word, forever." },
    { icon: "🌻", title: "Thank you for helping it bloom", body: "Your language needs people like you to keep fully existing." },
    { icon: "🧊", title: "Nothing melts, everything stays", body: "Unlike memory, what you just wrote never fades away." },
    { icon: "🐦", title: "A word flying far", body: "It can now be heard by someone on the other side of the world." },
    { icon: "🌈", title: "Thank you for this extra colour", body: "Every contribution adds a little more richness to what your language becomes." },
    { icon: "🧺", title: "Harvested with care", body: "What you just gave joins a patient harvest, built one word at a time." },
    { icon: "🕊️", title: "Already flying further than you", body: "Your contribution now belongs to everyone, forever." },
    { icon: "🌺", title: "Sincere recognition", body: "This kind of gesture doesn't get thanked often enough. So: thank you." },
    { icon: "🌤️", title: "One more ray of light", body: "Your contribution adds a bit of light to an immense collective effort." },
    { icon: "🧑‍🌾", title: "Thank you for sowing", body: "Someone else will one day harvest what you just planted." },
    { icon: "🏮", title: "A lantern lit", body: "What you pass on today will light someone's path tomorrow." },
    { icon: "🎼", title: "One more line added to the score", body: "Your language is written by many voices, and yours truly counts." },
    { icon: "🧩", title: "One more piece of the puzzle", body: "Your language comes together, piece by piece, thanks to gestures like yours." },
    { icon: "🌕", title: "Thank you for what you just did", body: "Simple to say, sincerely meant: what you do has real value." },
    { icon: "🐚", title: "An echo that will carry far", body: "This word will resonate long after you, for someone you'll never know." },
    { icon: "🧭", title: "You're showing the way", body: "Thanks to gestures like this one, your language stays reachable to anyone who wants to learn it." },
    { icon: "🌷", title: "Thank you for thinking of it", body: "Many put it off. You just did it. Thank you." },
    { icon: "🪵", title: "One more log on the fire", body: "Your contribution keeps alive a flame nobody wants to see go out." },
    { icon: "🌀", title: "It travels far, it stays close", body: "Your voice joins those of a whole community, and it keeps its full place." },
    { icon: "🧡", title: "It gets noticed", body: "Every contribution is counted, kept, useful. Yours too, starting now." },
    { icon: "🕸️", title: "One more thread in the weave", body: "Your language is woven from thousands of small gestures like this one. Thank you for being part of it." },
    { icon: "🌌", title: "One more star", body: "Alone, it looks small. Together with all the others, it lights up a whole sky." },
    { icon: "🍂", title: "Nothing falls into oblivion", body: "What you just gave won't share the fate of dead leaves: it stays, this one." },
    { icon: "🧑‍🍼", title: "For the generations to come", body: "A child not yet born might one day learn this word because of you." },
    { icon: "🪴", title: "Thank you for watering this project", body: "A living language needs regular care. You just gave it some." },
    { icon: "🎋", title: "One more sprout", body: "Every contribution grows, a little more, what will one day become a real living dictionary." },
    { icon: "🧊", title: "Preserved, not frozen", body: "What you just said or wrote stays alive, searchable, useful to whoever needs it." },
    { icon: "🏹", title: "It reaches far", body: "A word given today can be discovered by someone a very long time from now." },
    { icon: "🌬️", title: "Your voice carries", body: "It now travels beyond this page, all the way to other ears." },
    { icon: "🪞", title: "A faithful reflection of your language", body: "What you just gave is authentic, and that's exactly what matters." },
    { icon: "🧑‍🏫", title: "You're passing it on, like a teacher would", body: "This simple gesture is, in truth, an act of transmission, in the fullest sense of the word." },
    { icon: "🎇", title: "One more spark", body: "It may look small. Multiplied by hundreds of others, it becomes a fire." },
    { icon: "🧑‍🎨", title: "You're shaping something lasting", body: "Your language is also built like a collective work, one word at a time." },
    { icon: "🌒", title: "Thank you for this moment given", body: "You could have done something else. You chose your language. That's worth noticing." },
    { icon: "🧑‍🤝‍🧑", title: "A human chain, one more link", body: "Before you, others passed it on. After you, others will learn. You stand between the two, and that matters." },
    { icon: "🌾", title: "Every grain counts toward the harvest", body: "A solid foundation is built exactly like this: gesture after gesture, word after word." },
    { icon: "🕯️", title: "A flame kept alive", body: "Your language won't go out as long as people like you keep feeding it." },
    { icon: "🎁", title: "An unexpected gift", body: "Nobody made you do this. That's precisely what makes it precious." },
    { icon: "🪷", title: "It blooms slowly", body: "Your language doesn't grow all at once, but contribution by contribution. Yours is fully part of it." },
    { icon: "🧑‍🚀", title: "You're aiming far, without even knowing it", body: "This word you just left could one day help an artificial intelligence understand your language better." },
    { icon: "🌗", title: "Thank you for this small step", body: "Small steps, repeated, build the greatest paths. Yours has just been taken." },
    { icon: "🧺", title: "One more hand in the harvest", body: "What you just brought joins that of a whole patient and determined community." },
    { icon: "🌤️", title: "A word with real weight", body: "No hollow phrase here: what you do carries real weight for your language and for those who'll speak it tomorrow." },
    { icon: "🪁", title: "It rises, carried by everyone", body: "Your contribution joins the others and, together, they lift your language a little higher." },
    { icon: "🧑‍👩‍👧", title: "From one generation to the next", body: "What you pass on today could well be what your grandchild learns, one day." },
    { icon: "🌼", title: "A simple gesture, a deep effect", body: "You may not see it yet, but what you just did truly matters." },
    { icon: "🧑‍🔬", title: "A precious piece of data for the future", body: "This word enriches a corpus that will serve linguists as much as future keyboards for your language." },
    { icon: "🌅", title: "A new day for your language", body: "Every contribution pushes a little further away the risk of it one day being forgotten." },
    { icon: "🧑‍🎤", title: "Your voice has value", body: "It carries an accent, a rhythm, a music that no one else can give in your place." },
    { icon: "🪢", title: "A knot that holds", body: "What you just did ties a little more solidly your language's past to its future." },
    { icon: "🌟", title: "You're part of the story", body: "In a few years, people will be able to say that people like you kept this language alive." },
    { icon: "🧑‍🌾", title: "Thank you for this shared harvest", body: "What you give today will feed someone's curiosity, one day." },
    { icon: "🕊️", title: "Freed, passed on, kept", body: "Your word no longer belongs only to you: it now belongs to the whole community, forever." },
    { icon: "🌤️", title: "Noticed, appreciated", body: "What you just did doesn't go unnoticed, even if no one is there to see you do it." },
    { icon: "🧑‍🏭", title: "One more craftsperson", body: "Your language is built by hand, contribution after contribution, and you're one of its makers." },
    { icon: "🌙", title: "Thank you for this moment", body: "Morning, evening, or the middle of the night, this moment you give your language matters." },
    { icon: "🌾", title: "Your share of the harvest", body: "Small on its own, essential once joined with all the others." },
    { icon: "🧑‍🤝‍🧑", title: "Together, we go further", body: "Alone, this word would stay just a word. With the others, it becomes a living dictionary." },
    { icon: "🕯️", title: "It doesn't go out", body: "What you just passed on will keep existing long after this simple moment." },
    { icon: "🌱", title: "The tree that grows, slowly", body: "A fragile sprout today. With time and everyone's effort, it will become a tree." },
    { icon: "💫", title: "Thank you, from the heart", body: "What you just did is small on the scale of a life, immense on the scale of a language." },
    { icon: "🧑‍🎓", title: "You're becoming a guardian of your language", body: "That role isn't improvised. It's built exactly the way you just did it." },
    { icon: "🌤️", title: "It asks for nothing in return", body: "And that's precisely why what you just gave carries so much value." },
    { icon: "🧑‍🦳", title: "A bridge to the elders", body: "This word you just passed on may already have lived in your grandparents' mouths." },
    { icon: "🌾", title: "Sown today, harvested tomorrow", body: "No one knows yet who will learn this word because of you. That's the beauty of the gesture." },
    { icon: "🧑‍🚒", title: "You're protecting something fragile", body: "A language can fade away in silence. Because of you, this one resists a little longer." },
    { icon: "🌻", title: "It blooms because of you", body: "Your language needs constant care, and you just gave it some." },
    { icon: "🧑‍🎨", title: "One more brushstroke on the painting", body: "Your language is painted collectively, and your contribution adds a real colour to it." },
    { icon: "🕰️", title: "Time won't erase it", body: "Unlike so many things, what you just left behind will last." },
    { icon: "🌗", title: "A small step, a big meaning", body: "From afar, it's just a word. Up close, it's an act of loyalty to your language." },
    { icon: "🧑‍🤝‍🧑", title: "Your generosity speaks volumes", body: "You gave your time without being asked twice. Thank you for that." },
    { icon: "🌈", title: "Your language gains one more shade", body: "Every added word makes the palette a little more complete, a little truer to what it really is." },
    { icon: "🧑‍🍳", title: "A recipe passed down", body: "Like a family recipe, your language is handed down from person to person. Thank you for taking part." },
    { icon: "🌍", title: "One word, a worldwide reach", body: "It's now reachable from anywhere in the world. A small gesture, an immense reach." },
    { icon: "🧑‍⚕️", title: "You're taking care of your language", body: "The way you'd care for someone fragile and dear, steadily, attentively. Thank you." },
    { icon: "🌟", title: "What you're doing is rare", body: "Many of the world's languages have no one doing what you just did. You did." },
    { icon: "🧑‍🏫", title: "A quiet lesson", body: "Without knowing it, you may have just taught something to someone you'll never meet." },
    { icon: "🌙", title: "Even at night, your language moves forward", body: "Whatever the hour you contribute, what you give counts exactly the same." },
    { icon: "🧑‍🚀", title: "You're writing a piece of the future", body: "This word could become part of the very first digital tools for your language." },
    { icon: "🌾", title: "A harvest that never ends", body: "Every contribution calls for another, and the harvest keeps growing." },
    { icon: "🧑‍🎤", title: "Your voice is like no other", body: "It carries something no one else can pass on in your place." },
    { icon: "🌤️", title: "A moment, a lasting mark", body: "What you just did lasted a few seconds. Its effect will last much longer." },
    { icon: "🧑‍🏭", title: "Building, one word at a time", body: "The greatest libraries are always built this way: patiently, contribution after contribution." },
    { icon: "🌺", title: "You won't be forgotten", body: "Your contribution stays linked to you, to your name if you wish, forever." },
    { icon: "🕊️", title: "A flight that starts here", body: "This word leaves from you and can now land anywhere, with anyone." },
    { icon: "🧑‍🌾", title: "The land remembers who tended it", body: "Your language will, in its own way, remember what you just brought to it." },
    { icon: "🌱", title: "Quiet today, essential tomorrow", body: "What you plant now may become self-evident for future generations." },
    { icon: "🧑‍🎓", title: "You learn by giving", body: "By passing this word on, you're also strengthening your own bond with your language." },
    { icon: "🌤️", title: "Thank you for choosing your language, today", body: "Out of everything you could have done, you chose this. That matters enormously." },
    { icon: "🧑‍🤝‍🧑", title: "A link you don't always see", body: "But without it, the whole chain of transmission would be more fragile. Thank you for being one." },
    { icon: "🌾", title: "A seed that asks for nothing", body: "It grows in silence, without demanding attention. Just like your contribution today." },
    { icon: "🕯️", title: "Keeping the flame, together", body: "A language lives as long as people keep contributing to it. You just did your part." },
    { icon: "🌙", title: "It's never trivial", body: "One more word in the archive is one less word at risk of being forgotten one day." },
    { icon: "🧑‍🎨", title: "A work made by many hands", body: "Your language doesn't belong to any one person, it belongs to everyone who keeps it alive. You included." },
    { icon: "🌤️", title: "You're moving forward something bigger than yourself", body: "A patient, collective project, far bigger than this one contribution, yet one that needs it." },
    { icon: "🧑‍🍼", title: "One day, someone will say thank you", body: "Maybe not today, but one day someone will come across this word and be grateful for it." },
    { icon: "🌾", title: "Patiently, surely", body: "Your language isn't built all at once. It's built exactly like this, contribution after contribution, like this one." },
    { icon: "🧑‍🤝‍🧑", title: "Thank you for being part of the journey", body: "This project exists because of people like you, willing to give a bit of their time to your language." },
    { icon: "🌟", title: "One more proof that it matters", body: "Every new contribution confirms one thing: your language deserves to be preserved, and you believe it." },
    { icon: "🕊️", title: "Thank you for giving your voice, or your time", body: "Both carry the same value here: that of a sincere gesture for your language." },
    { icon: "💫", title: "This moment will remain, even a small one", body: "Every great library in the world started with a first word, then a second, just like this one." },
  ],
};

const MULTI = {
  fr: (k) => ({ title: k + " contributions confirmées", body: "Merci, chacune d'elles compte et vient enrichir la mémoire de ta langue." }),
  en: (k) => ({ title: k + " contributions confirmed", body: "Thank you, each one matters and enriches your language's memory." }),
};

/** Choisit le contenu du popup de remerciement.
    total = nb total d'envois confirmés sur cet appareil (compteur local, après ce tick) ;
    justConfirmed = nb d'envois confirmés PENDANT ce tick (peut être > 1, un seul popup alors) ;
    lang = "fr" | "en" (langue d'interface courante). */
export function pickThanksContent(total, justConfirmed, lang) {
  const L = (lang === "en") ? "en" : "fr";
  if (justConfirmed > 1) {
    const m = MULTI[L](justConfirmed);
    return { title: m.title, body: m.body, visual: "regular", icon: "🎉", skin: pickSkin() };
  }
  if (total === 1) {
    const f = FIRST[L];
    return { title: f.title, body: f.body, visual: "photo", skin: pickSkin() };
  }
  if (isMilestoneCount(total)) {
    const p = pick(MILESTONE_MSG[L]);
    return { title: ip(p.title, { n: total }), body: ip(p.body, { n: total }), visual: "milestone", n: total, skin: pickSkin() };
  }
  const p = pick(REGULAR[L]);
  return { title: p.title, body: p.body, visual: "regular", icon: p.icon, skin: pickSkin() };
}
